/*
SODACARDS Developer API

Testing PublicAPIServiceAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package sodacards

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/SODACARDS/sodacards-go"
)

func Test_sodacards_PublicAPIServiceAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PublicAPIServiceAPIService PublicAPIServiceGetBalance", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PublicAPIServiceAPI.PublicAPIServiceGetBalance(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
