/*
SODACARDS Developer API

Sell gift cards and game top-ups from your own systems.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sodacards

import (
	"encoding/json"
)

// checks if the SodacardsDevpublicV1Webhook type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SodacardsDevpublicV1Webhook{}

// SodacardsDevpublicV1Webhook Webhook is a registered endpoint. It never carries the signing secret.
type SodacardsDevpublicV1Webhook struct {
	// id identifies the endpoint.
	Id *string `json:"id,omitempty"`
	// url is the HTTPS endpoint events are delivered to.
	Url *string `json:"url,omitempty"`
	// events are the subscribed event types.
	Events []string `json:"events,omitempty"`
	// active is whether deliveries are currently sent to this endpoint.
	Active *bool `json:"active,omitempty"`
	// created_at is when the endpoint was registered (RFC 3339).
	CreatedAt *string `json:"createdAt,omitempty"`
}

// NewSodacardsDevpublicV1Webhook instantiates a new SodacardsDevpublicV1Webhook object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSodacardsDevpublicV1Webhook() *SodacardsDevpublicV1Webhook {
	this := SodacardsDevpublicV1Webhook{}
	return &this
}

// NewSodacardsDevpublicV1WebhookWithDefaults instantiates a new SodacardsDevpublicV1Webhook object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSodacardsDevpublicV1WebhookWithDefaults() *SodacardsDevpublicV1Webhook {
	this := SodacardsDevpublicV1Webhook{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1Webhook) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1Webhook) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1Webhook) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *SodacardsDevpublicV1Webhook) SetId(v string) {
	o.Id = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1Webhook) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1Webhook) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1Webhook) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *SodacardsDevpublicV1Webhook) SetUrl(v string) {
	o.Url = &v
}

// GetEvents returns the Events field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1Webhook) GetEvents() []string {
	if o == nil || IsNil(o.Events) {
		var ret []string
		return ret
	}
	return o.Events
}

// GetEventsOk returns a tuple with the Events field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1Webhook) GetEventsOk() ([]string, bool) {
	if o == nil || IsNil(o.Events) {
		return nil, false
	}
	return o.Events, true
}

// HasEvents returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1Webhook) HasEvents() bool {
	if o != nil && !IsNil(o.Events) {
		return true
	}

	return false
}

// SetEvents gets a reference to the given []string and assigns it to the Events field.
func (o *SodacardsDevpublicV1Webhook) SetEvents(v []string) {
	o.Events = v
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1Webhook) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1Webhook) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1Webhook) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *SodacardsDevpublicV1Webhook) SetActive(v bool) {
	o.Active = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1Webhook) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1Webhook) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1Webhook) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *SodacardsDevpublicV1Webhook) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

func (o SodacardsDevpublicV1Webhook) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SodacardsDevpublicV1Webhook) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Events) {
		toSerialize["events"] = o.Events
	}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	return toSerialize, nil
}

type NullableSodacardsDevpublicV1Webhook struct {
	value *SodacardsDevpublicV1Webhook
	isSet bool
}

func (v NullableSodacardsDevpublicV1Webhook) Get() *SodacardsDevpublicV1Webhook {
	return v.value
}

func (v *NullableSodacardsDevpublicV1Webhook) Set(val *SodacardsDevpublicV1Webhook) {
	v.value = val
	v.isSet = true
}

func (v NullableSodacardsDevpublicV1Webhook) IsSet() bool {
	return v.isSet
}

func (v *NullableSodacardsDevpublicV1Webhook) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSodacardsDevpublicV1Webhook(val *SodacardsDevpublicV1Webhook) *NullableSodacardsDevpublicV1Webhook {
	return &NullableSodacardsDevpublicV1Webhook{value: val, isSet: true}
}

func (v NullableSodacardsDevpublicV1Webhook) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSodacardsDevpublicV1Webhook) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


