/*
SODACARDS Developer API

Sell gift cards and game top-ups from your own systems.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sodacards

import (
	"encoding/json"
)

// checks if the SodacardsDevpublicV1GetBalanceResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SodacardsDevpublicV1GetBalanceResponse{}

// SodacardsDevpublicV1GetBalanceResponse struct for SodacardsDevpublicV1GetBalanceResponse
type SodacardsDevpublicV1GetBalanceResponse struct {
	// balance is the reseller's prepaid wallet balance. For a test key it is a  fixed sandbox value, clearly not the production wallet.
	Balance *SodacardsDevpublicV1Money `json:"balance,omitempty"`
}

// NewSodacardsDevpublicV1GetBalanceResponse instantiates a new SodacardsDevpublicV1GetBalanceResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSodacardsDevpublicV1GetBalanceResponse() *SodacardsDevpublicV1GetBalanceResponse {
	this := SodacardsDevpublicV1GetBalanceResponse{}
	return &this
}

// NewSodacardsDevpublicV1GetBalanceResponseWithDefaults instantiates a new SodacardsDevpublicV1GetBalanceResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSodacardsDevpublicV1GetBalanceResponseWithDefaults() *SodacardsDevpublicV1GetBalanceResponse {
	this := SodacardsDevpublicV1GetBalanceResponse{}
	return &this
}

// GetBalance returns the Balance field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1GetBalanceResponse) GetBalance() SodacardsDevpublicV1Money {
	if o == nil || IsNil(o.Balance) {
		var ret SodacardsDevpublicV1Money
		return ret
	}
	return *o.Balance
}

// GetBalanceOk returns a tuple with the Balance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1GetBalanceResponse) GetBalanceOk() (*SodacardsDevpublicV1Money, bool) {
	if o == nil || IsNil(o.Balance) {
		return nil, false
	}
	return o.Balance, true
}

// HasBalance returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1GetBalanceResponse) HasBalance() bool {
	if o != nil && !IsNil(o.Balance) {
		return true
	}

	return false
}

// SetBalance gets a reference to the given SodacardsDevpublicV1Money and assigns it to the Balance field.
func (o *SodacardsDevpublicV1GetBalanceResponse) SetBalance(v SodacardsDevpublicV1Money) {
	o.Balance = &v
}

func (o SodacardsDevpublicV1GetBalanceResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SodacardsDevpublicV1GetBalanceResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Balance) {
		toSerialize["balance"] = o.Balance
	}
	return toSerialize, nil
}

type NullableSodacardsDevpublicV1GetBalanceResponse struct {
	value *SodacardsDevpublicV1GetBalanceResponse
	isSet bool
}

func (v NullableSodacardsDevpublicV1GetBalanceResponse) Get() *SodacardsDevpublicV1GetBalanceResponse {
	return v.value
}

func (v *NullableSodacardsDevpublicV1GetBalanceResponse) Set(val *SodacardsDevpublicV1GetBalanceResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSodacardsDevpublicV1GetBalanceResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSodacardsDevpublicV1GetBalanceResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSodacardsDevpublicV1GetBalanceResponse(val *SodacardsDevpublicV1GetBalanceResponse) *NullableSodacardsDevpublicV1GetBalanceResponse {
	return &NullableSodacardsDevpublicV1GetBalanceResponse{value: val, isSet: true}
}

func (v NullableSodacardsDevpublicV1GetBalanceResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSodacardsDevpublicV1GetBalanceResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


