/*
SODACARDS Developer API

Sell gift cards and game top-ups from your own systems.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sodacards

import (
	"encoding/json"
)

// checks if the SodacardsDevpublicV1InputFieldSpec type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SodacardsDevpublicV1InputFieldSpec{}

// SodacardsDevpublicV1InputFieldSpec InputFieldSpec describes one purchase-form field a product requires, so a  developer can build and validate an order line before placing it. Its value is  submitted on OrderLine.input_fields, keyed by this field's key.
type SodacardsDevpublicV1InputFieldSpec struct {
	// key is the field's machine name and the key to use in  OrderLine.input_fields, e.g. \"player_id\".
	Key *string `json:"key,omitempty"`
	// type is how to render and validate the value: \"text\", \"number\" or \"select\".
	Type *string `json:"type,omitempty"`
	// required is true when an order line for this product must carry this field.
	Required *bool `json:"required,omitempty"`
	// regex, when present, is a regular expression the submitted value must match  (text and number fields). Empty when there is no pattern constraint.
	Regex *string `json:"regex,omitempty"`
	// options are the allowed values of a \"select\" field, in display order. Empty  for text and number fields.
	Options []SodacardsDevpublicV1InputFieldOption `json:"options,omitempty"`
}

// NewSodacardsDevpublicV1InputFieldSpec instantiates a new SodacardsDevpublicV1InputFieldSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSodacardsDevpublicV1InputFieldSpec() *SodacardsDevpublicV1InputFieldSpec {
	this := SodacardsDevpublicV1InputFieldSpec{}
	return &this
}

// NewSodacardsDevpublicV1InputFieldSpecWithDefaults instantiates a new SodacardsDevpublicV1InputFieldSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSodacardsDevpublicV1InputFieldSpecWithDefaults() *SodacardsDevpublicV1InputFieldSpec {
	this := SodacardsDevpublicV1InputFieldSpec{}
	return &this
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1InputFieldSpec) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1InputFieldSpec) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1InputFieldSpec) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *SodacardsDevpublicV1InputFieldSpec) SetKey(v string) {
	o.Key = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1InputFieldSpec) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1InputFieldSpec) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1InputFieldSpec) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *SodacardsDevpublicV1InputFieldSpec) SetType(v string) {
	o.Type = &v
}

// GetRequired returns the Required field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1InputFieldSpec) GetRequired() bool {
	if o == nil || IsNil(o.Required) {
		var ret bool
		return ret
	}
	return *o.Required
}

// GetRequiredOk returns a tuple with the Required field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1InputFieldSpec) GetRequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.Required) {
		return nil, false
	}
	return o.Required, true
}

// HasRequired returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1InputFieldSpec) HasRequired() bool {
	if o != nil && !IsNil(o.Required) {
		return true
	}

	return false
}

// SetRequired gets a reference to the given bool and assigns it to the Required field.
func (o *SodacardsDevpublicV1InputFieldSpec) SetRequired(v bool) {
	o.Required = &v
}

// GetRegex returns the Regex field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1InputFieldSpec) GetRegex() string {
	if o == nil || IsNil(o.Regex) {
		var ret string
		return ret
	}
	return *o.Regex
}

// GetRegexOk returns a tuple with the Regex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1InputFieldSpec) GetRegexOk() (*string, bool) {
	if o == nil || IsNil(o.Regex) {
		return nil, false
	}
	return o.Regex, true
}

// HasRegex returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1InputFieldSpec) HasRegex() bool {
	if o != nil && !IsNil(o.Regex) {
		return true
	}

	return false
}

// SetRegex gets a reference to the given string and assigns it to the Regex field.
func (o *SodacardsDevpublicV1InputFieldSpec) SetRegex(v string) {
	o.Regex = &v
}

// GetOptions returns the Options field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1InputFieldSpec) GetOptions() []SodacardsDevpublicV1InputFieldOption {
	if o == nil || IsNil(o.Options) {
		var ret []SodacardsDevpublicV1InputFieldOption
		return ret
	}
	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1InputFieldSpec) GetOptionsOk() ([]SodacardsDevpublicV1InputFieldOption, bool) {
	if o == nil || IsNil(o.Options) {
		return nil, false
	}
	return o.Options, true
}

// HasOptions returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1InputFieldSpec) HasOptions() bool {
	if o != nil && !IsNil(o.Options) {
		return true
	}

	return false
}

// SetOptions gets a reference to the given []SodacardsDevpublicV1InputFieldOption and assigns it to the Options field.
func (o *SodacardsDevpublicV1InputFieldSpec) SetOptions(v []SodacardsDevpublicV1InputFieldOption) {
	o.Options = v
}

func (o SodacardsDevpublicV1InputFieldSpec) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SodacardsDevpublicV1InputFieldSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Required) {
		toSerialize["required"] = o.Required
	}
	if !IsNil(o.Regex) {
		toSerialize["regex"] = o.Regex
	}
	if !IsNil(o.Options) {
		toSerialize["options"] = o.Options
	}
	return toSerialize, nil
}

type NullableSodacardsDevpublicV1InputFieldSpec struct {
	value *SodacardsDevpublicV1InputFieldSpec
	isSet bool
}

func (v NullableSodacardsDevpublicV1InputFieldSpec) Get() *SodacardsDevpublicV1InputFieldSpec {
	return v.value
}

func (v *NullableSodacardsDevpublicV1InputFieldSpec) Set(val *SodacardsDevpublicV1InputFieldSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableSodacardsDevpublicV1InputFieldSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableSodacardsDevpublicV1InputFieldSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSodacardsDevpublicV1InputFieldSpec(val *SodacardsDevpublicV1InputFieldSpec) *NullableSodacardsDevpublicV1InputFieldSpec {
	return &NullableSodacardsDevpublicV1InputFieldSpec{value: val, isSet: true}
}

func (v NullableSodacardsDevpublicV1InputFieldSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSodacardsDevpublicV1InputFieldSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


