/*
SODACARDS Developer API

Sell gift cards and game top-ups from your own systems.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sodacards

import (
	"encoding/json"
)

// checks if the SodacardsDevpublicV1ListWebhooksResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SodacardsDevpublicV1ListWebhooksResponse{}

// SodacardsDevpublicV1ListWebhooksResponse struct for SodacardsDevpublicV1ListWebhooksResponse
type SodacardsDevpublicV1ListWebhooksResponse struct {
	// webhooks are the reseller's registered endpoints.
	Webhooks []SodacardsDevpublicV1Webhook `json:"webhooks,omitempty"`
}

// NewSodacardsDevpublicV1ListWebhooksResponse instantiates a new SodacardsDevpublicV1ListWebhooksResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSodacardsDevpublicV1ListWebhooksResponse() *SodacardsDevpublicV1ListWebhooksResponse {
	this := SodacardsDevpublicV1ListWebhooksResponse{}
	return &this
}

// NewSodacardsDevpublicV1ListWebhooksResponseWithDefaults instantiates a new SodacardsDevpublicV1ListWebhooksResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSodacardsDevpublicV1ListWebhooksResponseWithDefaults() *SodacardsDevpublicV1ListWebhooksResponse {
	this := SodacardsDevpublicV1ListWebhooksResponse{}
	return &this
}

// GetWebhooks returns the Webhooks field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1ListWebhooksResponse) GetWebhooks() []SodacardsDevpublicV1Webhook {
	if o == nil || IsNil(o.Webhooks) {
		var ret []SodacardsDevpublicV1Webhook
		return ret
	}
	return o.Webhooks
}

// GetWebhooksOk returns a tuple with the Webhooks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1ListWebhooksResponse) GetWebhooksOk() ([]SodacardsDevpublicV1Webhook, bool) {
	if o == nil || IsNil(o.Webhooks) {
		return nil, false
	}
	return o.Webhooks, true
}

// HasWebhooks returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1ListWebhooksResponse) HasWebhooks() bool {
	if o != nil && !IsNil(o.Webhooks) {
		return true
	}

	return false
}

// SetWebhooks gets a reference to the given []SodacardsDevpublicV1Webhook and assigns it to the Webhooks field.
func (o *SodacardsDevpublicV1ListWebhooksResponse) SetWebhooks(v []SodacardsDevpublicV1Webhook) {
	o.Webhooks = v
}

func (o SodacardsDevpublicV1ListWebhooksResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SodacardsDevpublicV1ListWebhooksResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Webhooks) {
		toSerialize["webhooks"] = o.Webhooks
	}
	return toSerialize, nil
}

type NullableSodacardsDevpublicV1ListWebhooksResponse struct {
	value *SodacardsDevpublicV1ListWebhooksResponse
	isSet bool
}

func (v NullableSodacardsDevpublicV1ListWebhooksResponse) Get() *SodacardsDevpublicV1ListWebhooksResponse {
	return v.value
}

func (v *NullableSodacardsDevpublicV1ListWebhooksResponse) Set(val *SodacardsDevpublicV1ListWebhooksResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSodacardsDevpublicV1ListWebhooksResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSodacardsDevpublicV1ListWebhooksResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSodacardsDevpublicV1ListWebhooksResponse(val *SodacardsDevpublicV1ListWebhooksResponse) *NullableSodacardsDevpublicV1ListWebhooksResponse {
	return &NullableSodacardsDevpublicV1ListWebhooksResponse{value: val, isSet: true}
}

func (v NullableSodacardsDevpublicV1ListWebhooksResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSodacardsDevpublicV1ListWebhooksResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


