/*
SODACARDS Developer API

Sell gift cards and game top-ups from your own systems.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sodacards

import (
	"encoding/json"
)

// checks if the SodacardsDevpublicV1DeleteWebhookRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SodacardsDevpublicV1DeleteWebhookRequest{}

// SodacardsDevpublicV1DeleteWebhookRequest struct for SodacardsDevpublicV1DeleteWebhookRequest
type SodacardsDevpublicV1DeleteWebhookRequest struct {
	// id is the webhook endpoint to remove.
	Id *string `json:"id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SodacardsDevpublicV1DeleteWebhookRequest SodacardsDevpublicV1DeleteWebhookRequest

// NewSodacardsDevpublicV1DeleteWebhookRequest instantiates a new SodacardsDevpublicV1DeleteWebhookRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSodacardsDevpublicV1DeleteWebhookRequest() *SodacardsDevpublicV1DeleteWebhookRequest {
	this := SodacardsDevpublicV1DeleteWebhookRequest{}
	return &this
}

// NewSodacardsDevpublicV1DeleteWebhookRequestWithDefaults instantiates a new SodacardsDevpublicV1DeleteWebhookRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSodacardsDevpublicV1DeleteWebhookRequestWithDefaults() *SodacardsDevpublicV1DeleteWebhookRequest {
	this := SodacardsDevpublicV1DeleteWebhookRequest{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1DeleteWebhookRequest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1DeleteWebhookRequest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1DeleteWebhookRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *SodacardsDevpublicV1DeleteWebhookRequest) SetId(v string) {
	o.Id = &v
}

func (o SodacardsDevpublicV1DeleteWebhookRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SodacardsDevpublicV1DeleteWebhookRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SodacardsDevpublicV1DeleteWebhookRequest) UnmarshalJSON(data []byte) (err error) {
	varSodacardsDevpublicV1DeleteWebhookRequest := _SodacardsDevpublicV1DeleteWebhookRequest{}

	err = json.Unmarshal(data, &varSodacardsDevpublicV1DeleteWebhookRequest)

	if err != nil {
		return err
	}

	*o = SodacardsDevpublicV1DeleteWebhookRequest(varSodacardsDevpublicV1DeleteWebhookRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSodacardsDevpublicV1DeleteWebhookRequest struct {
	value *SodacardsDevpublicV1DeleteWebhookRequest
	isSet bool
}

func (v NullableSodacardsDevpublicV1DeleteWebhookRequest) Get() *SodacardsDevpublicV1DeleteWebhookRequest {
	return v.value
}

func (v *NullableSodacardsDevpublicV1DeleteWebhookRequest) Set(val *SodacardsDevpublicV1DeleteWebhookRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSodacardsDevpublicV1DeleteWebhookRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSodacardsDevpublicV1DeleteWebhookRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSodacardsDevpublicV1DeleteWebhookRequest(val *SodacardsDevpublicV1DeleteWebhookRequest) *NullableSodacardsDevpublicV1DeleteWebhookRequest {
	return &NullableSodacardsDevpublicV1DeleteWebhookRequest{value: val, isSet: true}
}

func (v NullableSodacardsDevpublicV1DeleteWebhookRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSodacardsDevpublicV1DeleteWebhookRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


