/*
SODACARDS Developer API

Sell gift cards and game top-ups from your own systems.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sodacards

import (
	"encoding/json"
)

// checks if the SodacardsDevpublicV1OrderItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SodacardsDevpublicV1OrderItem{}

// SodacardsDevpublicV1OrderItem OrderItem is one line of an order.
type SodacardsDevpublicV1OrderItem struct {
	// product_id is the product ordered on this line.
	ProductId *string `json:"productId,omitempty"`
	// name is the product name at order time.
	Name *string `json:"name,omitempty"`
	// unit_price is the price of one unit, in FCFA.
	UnitPrice *SodacardsDevpublicV1Money `json:"unitPrice,omitempty"`
	// quantity is how many units were ordered.
	Quantity *int32 `json:"quantity,omitempty"`
	// line_total is unit_price times quantity, in FCFA.
	LineTotal *SodacardsDevpublicV1Money `json:"lineTotal,omitempty"`
	// input_fields are the purchase-form values submitted for this line.
	InputFields map[string]string `json:"inputFields,omitempty"`
}

// NewSodacardsDevpublicV1OrderItem instantiates a new SodacardsDevpublicV1OrderItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSodacardsDevpublicV1OrderItem() *SodacardsDevpublicV1OrderItem {
	this := SodacardsDevpublicV1OrderItem{}
	return &this
}

// NewSodacardsDevpublicV1OrderItemWithDefaults instantiates a new SodacardsDevpublicV1OrderItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSodacardsDevpublicV1OrderItemWithDefaults() *SodacardsDevpublicV1OrderItem {
	this := SodacardsDevpublicV1OrderItem{}
	return &this
}

// GetProductId returns the ProductId field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1OrderItem) GetProductId() string {
	if o == nil || IsNil(o.ProductId) {
		var ret string
		return ret
	}
	return *o.ProductId
}

// GetProductIdOk returns a tuple with the ProductId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1OrderItem) GetProductIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProductId) {
		return nil, false
	}
	return o.ProductId, true
}

// HasProductId returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1OrderItem) HasProductId() bool {
	if o != nil && !IsNil(o.ProductId) {
		return true
	}

	return false
}

// SetProductId gets a reference to the given string and assigns it to the ProductId field.
func (o *SodacardsDevpublicV1OrderItem) SetProductId(v string) {
	o.ProductId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1OrderItem) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1OrderItem) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1OrderItem) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SodacardsDevpublicV1OrderItem) SetName(v string) {
	o.Name = &v
}

// GetUnitPrice returns the UnitPrice field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1OrderItem) GetUnitPrice() SodacardsDevpublicV1Money {
	if o == nil || IsNil(o.UnitPrice) {
		var ret SodacardsDevpublicV1Money
		return ret
	}
	return *o.UnitPrice
}

// GetUnitPriceOk returns a tuple with the UnitPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1OrderItem) GetUnitPriceOk() (*SodacardsDevpublicV1Money, bool) {
	if o == nil || IsNil(o.UnitPrice) {
		return nil, false
	}
	return o.UnitPrice, true
}

// HasUnitPrice returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1OrderItem) HasUnitPrice() bool {
	if o != nil && !IsNil(o.UnitPrice) {
		return true
	}

	return false
}

// SetUnitPrice gets a reference to the given SodacardsDevpublicV1Money and assigns it to the UnitPrice field.
func (o *SodacardsDevpublicV1OrderItem) SetUnitPrice(v SodacardsDevpublicV1Money) {
	o.UnitPrice = &v
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1OrderItem) GetQuantity() int32 {
	if o == nil || IsNil(o.Quantity) {
		var ret int32
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1OrderItem) GetQuantityOk() (*int32, bool) {
	if o == nil || IsNil(o.Quantity) {
		return nil, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1OrderItem) HasQuantity() bool {
	if o != nil && !IsNil(o.Quantity) {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given int32 and assigns it to the Quantity field.
func (o *SodacardsDevpublicV1OrderItem) SetQuantity(v int32) {
	o.Quantity = &v
}

// GetLineTotal returns the LineTotal field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1OrderItem) GetLineTotal() SodacardsDevpublicV1Money {
	if o == nil || IsNil(o.LineTotal) {
		var ret SodacardsDevpublicV1Money
		return ret
	}
	return *o.LineTotal
}

// GetLineTotalOk returns a tuple with the LineTotal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1OrderItem) GetLineTotalOk() (*SodacardsDevpublicV1Money, bool) {
	if o == nil || IsNil(o.LineTotal) {
		return nil, false
	}
	return o.LineTotal, true
}

// HasLineTotal returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1OrderItem) HasLineTotal() bool {
	if o != nil && !IsNil(o.LineTotal) {
		return true
	}

	return false
}

// SetLineTotal gets a reference to the given SodacardsDevpublicV1Money and assigns it to the LineTotal field.
func (o *SodacardsDevpublicV1OrderItem) SetLineTotal(v SodacardsDevpublicV1Money) {
	o.LineTotal = &v
}

// GetInputFields returns the InputFields field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1OrderItem) GetInputFields() map[string]string {
	if o == nil || IsNil(o.InputFields) {
		var ret map[string]string
		return ret
	}
	return o.InputFields
}

// GetInputFieldsOk returns a tuple with the InputFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1OrderItem) GetInputFieldsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.InputFields) {
		return map[string]string{}, false
	}
	return o.InputFields, true
}

// HasInputFields returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1OrderItem) HasInputFields() bool {
	if o != nil && !IsNil(o.InputFields) {
		return true
	}

	return false
}

// SetInputFields gets a reference to the given map[string]string and assigns it to the InputFields field.
func (o *SodacardsDevpublicV1OrderItem) SetInputFields(v map[string]string) {
	o.InputFields = v
}

func (o SodacardsDevpublicV1OrderItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SodacardsDevpublicV1OrderItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ProductId) {
		toSerialize["productId"] = o.ProductId
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.UnitPrice) {
		toSerialize["unitPrice"] = o.UnitPrice
	}
	if !IsNil(o.Quantity) {
		toSerialize["quantity"] = o.Quantity
	}
	if !IsNil(o.LineTotal) {
		toSerialize["lineTotal"] = o.LineTotal
	}
	if !IsNil(o.InputFields) {
		toSerialize["inputFields"] = o.InputFields
	}
	return toSerialize, nil
}

type NullableSodacardsDevpublicV1OrderItem struct {
	value *SodacardsDevpublicV1OrderItem
	isSet bool
}

func (v NullableSodacardsDevpublicV1OrderItem) Get() *SodacardsDevpublicV1OrderItem {
	return v.value
}

func (v *NullableSodacardsDevpublicV1OrderItem) Set(val *SodacardsDevpublicV1OrderItem) {
	v.value = val
	v.isSet = true
}

func (v NullableSodacardsDevpublicV1OrderItem) IsSet() bool {
	return v.isSet
}

func (v *NullableSodacardsDevpublicV1OrderItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSodacardsDevpublicV1OrderItem(val *SodacardsDevpublicV1OrderItem) *NullableSodacardsDevpublicV1OrderItem {
	return &NullableSodacardsDevpublicV1OrderItem{value: val, isSet: true}
}

func (v NullableSodacardsDevpublicV1OrderItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSodacardsDevpublicV1OrderItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


