/*
SODACARDS Developer API

Sell gift cards and game top-ups from your own systems.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sodacards

import (
	"encoding/json"
)

// checks if the SodacardsDevpublicV1Money type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SodacardsDevpublicV1Money{}

// SodacardsDevpublicV1Money struct for SodacardsDevpublicV1Money
type SodacardsDevpublicV1Money struct {
	Amount *Amount `json:"amount,omitempty"`
	// currency is the ISO-4217 code, e.g. \"XOF\".
	Currency *string `json:"currency,omitempty"`
	// minor_unit_exponent is the currency's number of decimal places (0 for XOF,  2 for USD): amount divided by 10^minor_unit_exponent is the major-unit value.
	MinorUnitExponent *int32 `json:"minorUnitExponent,omitempty"`
}

// NewSodacardsDevpublicV1Money instantiates a new SodacardsDevpublicV1Money object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSodacardsDevpublicV1Money() *SodacardsDevpublicV1Money {
	this := SodacardsDevpublicV1Money{}
	return &this
}

// NewSodacardsDevpublicV1MoneyWithDefaults instantiates a new SodacardsDevpublicV1Money object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSodacardsDevpublicV1MoneyWithDefaults() *SodacardsDevpublicV1Money {
	this := SodacardsDevpublicV1Money{}
	return &this
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1Money) GetAmount() Amount {
	if o == nil || IsNil(o.Amount) {
		var ret Amount
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1Money) GetAmountOk() (*Amount, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1Money) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given Amount and assigns it to the Amount field.
func (o *SodacardsDevpublicV1Money) SetAmount(v Amount) {
	o.Amount = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1Money) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1Money) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1Money) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *SodacardsDevpublicV1Money) SetCurrency(v string) {
	o.Currency = &v
}

// GetMinorUnitExponent returns the MinorUnitExponent field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1Money) GetMinorUnitExponent() int32 {
	if o == nil || IsNil(o.MinorUnitExponent) {
		var ret int32
		return ret
	}
	return *o.MinorUnitExponent
}

// GetMinorUnitExponentOk returns a tuple with the MinorUnitExponent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1Money) GetMinorUnitExponentOk() (*int32, bool) {
	if o == nil || IsNil(o.MinorUnitExponent) {
		return nil, false
	}
	return o.MinorUnitExponent, true
}

// HasMinorUnitExponent returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1Money) HasMinorUnitExponent() bool {
	if o != nil && !IsNil(o.MinorUnitExponent) {
		return true
	}

	return false
}

// SetMinorUnitExponent gets a reference to the given int32 and assigns it to the MinorUnitExponent field.
func (o *SodacardsDevpublicV1Money) SetMinorUnitExponent(v int32) {
	o.MinorUnitExponent = &v
}

func (o SodacardsDevpublicV1Money) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SodacardsDevpublicV1Money) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.MinorUnitExponent) {
		toSerialize["minorUnitExponent"] = o.MinorUnitExponent
	}
	return toSerialize, nil
}

type NullableSodacardsDevpublicV1Money struct {
	value *SodacardsDevpublicV1Money
	isSet bool
}

func (v NullableSodacardsDevpublicV1Money) Get() *SodacardsDevpublicV1Money {
	return v.value
}

func (v *NullableSodacardsDevpublicV1Money) Set(val *SodacardsDevpublicV1Money) {
	v.value = val
	v.isSet = true
}

func (v NullableSodacardsDevpublicV1Money) IsSet() bool {
	return v.isSet
}

func (v *NullableSodacardsDevpublicV1Money) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSodacardsDevpublicV1Money(val *SodacardsDevpublicV1Money) *NullableSodacardsDevpublicV1Money {
	return &NullableSodacardsDevpublicV1Money{value: val, isSet: true}
}

func (v NullableSodacardsDevpublicV1Money) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSodacardsDevpublicV1Money) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


