/*
SODACARDS Developer API

Sell gift cards and game top-ups from your own systems.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sodacards

import (
	"encoding/json"
)

// checks if the SodacardsDevpublicV1ListOrdersResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SodacardsDevpublicV1ListOrdersResponse{}

// SodacardsDevpublicV1ListOrdersResponse struct for SodacardsDevpublicV1ListOrdersResponse
type SodacardsDevpublicV1ListOrdersResponse struct {
	// data is the page of orders, newest first.
	Data []SodacardsDevpublicV1Order `json:"data,omitempty"`
	// has_more is true when another page follows this one.
	HasMore *bool `json:"hasMore,omitempty"`
	// next_cursor fetches the next page. Empty on the last page.
	NextCursor *string `json:"nextCursor,omitempty"`
}

// NewSodacardsDevpublicV1ListOrdersResponse instantiates a new SodacardsDevpublicV1ListOrdersResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSodacardsDevpublicV1ListOrdersResponse() *SodacardsDevpublicV1ListOrdersResponse {
	this := SodacardsDevpublicV1ListOrdersResponse{}
	return &this
}

// NewSodacardsDevpublicV1ListOrdersResponseWithDefaults instantiates a new SodacardsDevpublicV1ListOrdersResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSodacardsDevpublicV1ListOrdersResponseWithDefaults() *SodacardsDevpublicV1ListOrdersResponse {
	this := SodacardsDevpublicV1ListOrdersResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1ListOrdersResponse) GetData() []SodacardsDevpublicV1Order {
	if o == nil || IsNil(o.Data) {
		var ret []SodacardsDevpublicV1Order
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1ListOrdersResponse) GetDataOk() ([]SodacardsDevpublicV1Order, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1ListOrdersResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []SodacardsDevpublicV1Order and assigns it to the Data field.
func (o *SodacardsDevpublicV1ListOrdersResponse) SetData(v []SodacardsDevpublicV1Order) {
	o.Data = v
}

// GetHasMore returns the HasMore field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1ListOrdersResponse) GetHasMore() bool {
	if o == nil || IsNil(o.HasMore) {
		var ret bool
		return ret
	}
	return *o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1ListOrdersResponse) GetHasMoreOk() (*bool, bool) {
	if o == nil || IsNil(o.HasMore) {
		return nil, false
	}
	return o.HasMore, true
}

// HasHasMore returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1ListOrdersResponse) HasHasMore() bool {
	if o != nil && !IsNil(o.HasMore) {
		return true
	}

	return false
}

// SetHasMore gets a reference to the given bool and assigns it to the HasMore field.
func (o *SodacardsDevpublicV1ListOrdersResponse) SetHasMore(v bool) {
	o.HasMore = &v
}

// GetNextCursor returns the NextCursor field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1ListOrdersResponse) GetNextCursor() string {
	if o == nil || IsNil(o.NextCursor) {
		var ret string
		return ret
	}
	return *o.NextCursor
}

// GetNextCursorOk returns a tuple with the NextCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1ListOrdersResponse) GetNextCursorOk() (*string, bool) {
	if o == nil || IsNil(o.NextCursor) {
		return nil, false
	}
	return o.NextCursor, true
}

// HasNextCursor returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1ListOrdersResponse) HasNextCursor() bool {
	if o != nil && !IsNil(o.NextCursor) {
		return true
	}

	return false
}

// SetNextCursor gets a reference to the given string and assigns it to the NextCursor field.
func (o *SodacardsDevpublicV1ListOrdersResponse) SetNextCursor(v string) {
	o.NextCursor = &v
}

func (o SodacardsDevpublicV1ListOrdersResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SodacardsDevpublicV1ListOrdersResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.HasMore) {
		toSerialize["hasMore"] = o.HasMore
	}
	if !IsNil(o.NextCursor) {
		toSerialize["nextCursor"] = o.NextCursor
	}
	return toSerialize, nil
}

type NullableSodacardsDevpublicV1ListOrdersResponse struct {
	value *SodacardsDevpublicV1ListOrdersResponse
	isSet bool
}

func (v NullableSodacardsDevpublicV1ListOrdersResponse) Get() *SodacardsDevpublicV1ListOrdersResponse {
	return v.value
}

func (v *NullableSodacardsDevpublicV1ListOrdersResponse) Set(val *SodacardsDevpublicV1ListOrdersResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSodacardsDevpublicV1ListOrdersResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSodacardsDevpublicV1ListOrdersResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSodacardsDevpublicV1ListOrdersResponse(val *SodacardsDevpublicV1ListOrdersResponse) *NullableSodacardsDevpublicV1ListOrdersResponse {
	return &NullableSodacardsDevpublicV1ListOrdersResponse{value: val, isSet: true}
}

func (v NullableSodacardsDevpublicV1ListOrdersResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSodacardsDevpublicV1ListOrdersResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


