/*
SODACARDS Developer API

Sell gift cards and game top-ups from your own systems.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sodacards

import (
	"encoding/json"
)

// checks if the SodacardsDevpublicV1InputFieldOption type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SodacardsDevpublicV1InputFieldOption{}

// SodacardsDevpublicV1InputFieldOption InputFieldOption is one allowed value of a \"select\" input field.
type SodacardsDevpublicV1InputFieldOption struct {
	// value is what to submit on OrderLine.input_fields for this option.
	Value *string `json:"value,omitempty"`
	// label is the human-readable display for the option.
	Label *string `json:"label,omitempty"`
	// parent_value gates a cascading option: the value of the parent field's option  that must be selected for this option to apply (e.g. a server option gated by  the chosen region). Empty when the option is not part of a cascade.
	ParentValue *string `json:"parentValue,omitempty"`
}

// NewSodacardsDevpublicV1InputFieldOption instantiates a new SodacardsDevpublicV1InputFieldOption object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSodacardsDevpublicV1InputFieldOption() *SodacardsDevpublicV1InputFieldOption {
	this := SodacardsDevpublicV1InputFieldOption{}
	return &this
}

// NewSodacardsDevpublicV1InputFieldOptionWithDefaults instantiates a new SodacardsDevpublicV1InputFieldOption object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSodacardsDevpublicV1InputFieldOptionWithDefaults() *SodacardsDevpublicV1InputFieldOption {
	this := SodacardsDevpublicV1InputFieldOption{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1InputFieldOption) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1InputFieldOption) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1InputFieldOption) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *SodacardsDevpublicV1InputFieldOption) SetValue(v string) {
	o.Value = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1InputFieldOption) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1InputFieldOption) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1InputFieldOption) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *SodacardsDevpublicV1InputFieldOption) SetLabel(v string) {
	o.Label = &v
}

// GetParentValue returns the ParentValue field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1InputFieldOption) GetParentValue() string {
	if o == nil || IsNil(o.ParentValue) {
		var ret string
		return ret
	}
	return *o.ParentValue
}

// GetParentValueOk returns a tuple with the ParentValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1InputFieldOption) GetParentValueOk() (*string, bool) {
	if o == nil || IsNil(o.ParentValue) {
		return nil, false
	}
	return o.ParentValue, true
}

// HasParentValue returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1InputFieldOption) HasParentValue() bool {
	if o != nil && !IsNil(o.ParentValue) {
		return true
	}

	return false
}

// SetParentValue gets a reference to the given string and assigns it to the ParentValue field.
func (o *SodacardsDevpublicV1InputFieldOption) SetParentValue(v string) {
	o.ParentValue = &v
}

func (o SodacardsDevpublicV1InputFieldOption) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SodacardsDevpublicV1InputFieldOption) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.ParentValue) {
		toSerialize["parentValue"] = o.ParentValue
	}
	return toSerialize, nil
}

type NullableSodacardsDevpublicV1InputFieldOption struct {
	value *SodacardsDevpublicV1InputFieldOption
	isSet bool
}

func (v NullableSodacardsDevpublicV1InputFieldOption) Get() *SodacardsDevpublicV1InputFieldOption {
	return v.value
}

func (v *NullableSodacardsDevpublicV1InputFieldOption) Set(val *SodacardsDevpublicV1InputFieldOption) {
	v.value = val
	v.isSet = true
}

func (v NullableSodacardsDevpublicV1InputFieldOption) IsSet() bool {
	return v.isSet
}

func (v *NullableSodacardsDevpublicV1InputFieldOption) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSodacardsDevpublicV1InputFieldOption(val *SodacardsDevpublicV1InputFieldOption) *NullableSodacardsDevpublicV1InputFieldOption {
	return &NullableSodacardsDevpublicV1InputFieldOption{value: val, isSet: true}
}

func (v NullableSodacardsDevpublicV1InputFieldOption) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSodacardsDevpublicV1InputFieldOption) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


