/*
SODACARDS Developer API

Sell gift cards and game top-ups from your own systems.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sodacards

import (
	"encoding/json"
)

// checks if the SodacardsDevpublicV1RotateWebhookSecretRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SodacardsDevpublicV1RotateWebhookSecretRequest{}

// SodacardsDevpublicV1RotateWebhookSecretRequest struct for SodacardsDevpublicV1RotateWebhookSecretRequest
type SodacardsDevpublicV1RotateWebhookSecretRequest struct {
	// id is the webhook endpoint whose signing secret to rotate.
	Id *string `json:"id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SodacardsDevpublicV1RotateWebhookSecretRequest SodacardsDevpublicV1RotateWebhookSecretRequest

// NewSodacardsDevpublicV1RotateWebhookSecretRequest instantiates a new SodacardsDevpublicV1RotateWebhookSecretRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSodacardsDevpublicV1RotateWebhookSecretRequest() *SodacardsDevpublicV1RotateWebhookSecretRequest {
	this := SodacardsDevpublicV1RotateWebhookSecretRequest{}
	return &this
}

// NewSodacardsDevpublicV1RotateWebhookSecretRequestWithDefaults instantiates a new SodacardsDevpublicV1RotateWebhookSecretRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSodacardsDevpublicV1RotateWebhookSecretRequestWithDefaults() *SodacardsDevpublicV1RotateWebhookSecretRequest {
	this := SodacardsDevpublicV1RotateWebhookSecretRequest{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1RotateWebhookSecretRequest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1RotateWebhookSecretRequest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1RotateWebhookSecretRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *SodacardsDevpublicV1RotateWebhookSecretRequest) SetId(v string) {
	o.Id = &v
}

func (o SodacardsDevpublicV1RotateWebhookSecretRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SodacardsDevpublicV1RotateWebhookSecretRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SodacardsDevpublicV1RotateWebhookSecretRequest) UnmarshalJSON(data []byte) (err error) {
	varSodacardsDevpublicV1RotateWebhookSecretRequest := _SodacardsDevpublicV1RotateWebhookSecretRequest{}

	err = json.Unmarshal(data, &varSodacardsDevpublicV1RotateWebhookSecretRequest)

	if err != nil {
		return err
	}

	*o = SodacardsDevpublicV1RotateWebhookSecretRequest(varSodacardsDevpublicV1RotateWebhookSecretRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSodacardsDevpublicV1RotateWebhookSecretRequest struct {
	value *SodacardsDevpublicV1RotateWebhookSecretRequest
	isSet bool
}

func (v NullableSodacardsDevpublicV1RotateWebhookSecretRequest) Get() *SodacardsDevpublicV1RotateWebhookSecretRequest {
	return v.value
}

func (v *NullableSodacardsDevpublicV1RotateWebhookSecretRequest) Set(val *SodacardsDevpublicV1RotateWebhookSecretRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSodacardsDevpublicV1RotateWebhookSecretRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSodacardsDevpublicV1RotateWebhookSecretRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSodacardsDevpublicV1RotateWebhookSecretRequest(val *SodacardsDevpublicV1RotateWebhookSecretRequest) *NullableSodacardsDevpublicV1RotateWebhookSecretRequest {
	return &NullableSodacardsDevpublicV1RotateWebhookSecretRequest{value: val, isSet: true}
}

func (v NullableSodacardsDevpublicV1RotateWebhookSecretRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSodacardsDevpublicV1RotateWebhookSecretRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


