/*
SODACARDS Developer API

Sell gift cards and game top-ups from your own systems.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sodacards

import (
	"encoding/json"
)

// checks if the SodacardsDevpublicV1Order type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SodacardsDevpublicV1Order{}

// SodacardsDevpublicV1Order Order is a placed order with its lines and current status. It never carries the  supplier cost.
type SodacardsDevpublicV1Order struct {
	// id identifies the order.
	Id *string `json:"id,omitempty"`
	// status is the order's current state: \"pending\", \"processing\", \"completed\",  \"failed\" or \"refunded\".
	Status *string `json:"status,omitempty"`
	// total is the amount charged for the order, in FCFA.
	Total *SodacardsDevpublicV1Money `json:"total,omitempty"`
	// created_at is when the order was placed (RFC 3339).
	CreatedAt *string `json:"createdAt,omitempty"`
	// reference is the identifier you attached at creation, empty if none.
	Reference *string `json:"reference,omitempty"`
	// lines are the ordered products.
	Lines []SodacardsDevpublicV1OrderItem `json:"lines,omitempty"`
}

// NewSodacardsDevpublicV1Order instantiates a new SodacardsDevpublicV1Order object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSodacardsDevpublicV1Order() *SodacardsDevpublicV1Order {
	this := SodacardsDevpublicV1Order{}
	return &this
}

// NewSodacardsDevpublicV1OrderWithDefaults instantiates a new SodacardsDevpublicV1Order object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSodacardsDevpublicV1OrderWithDefaults() *SodacardsDevpublicV1Order {
	this := SodacardsDevpublicV1Order{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1Order) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1Order) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1Order) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *SodacardsDevpublicV1Order) SetId(v string) {
	o.Id = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1Order) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1Order) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1Order) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *SodacardsDevpublicV1Order) SetStatus(v string) {
	o.Status = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1Order) GetTotal() SodacardsDevpublicV1Money {
	if o == nil || IsNil(o.Total) {
		var ret SodacardsDevpublicV1Money
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1Order) GetTotalOk() (*SodacardsDevpublicV1Money, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1Order) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given SodacardsDevpublicV1Money and assigns it to the Total field.
func (o *SodacardsDevpublicV1Order) SetTotal(v SodacardsDevpublicV1Money) {
	o.Total = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1Order) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1Order) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1Order) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *SodacardsDevpublicV1Order) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetReference returns the Reference field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1Order) GetReference() string {
	if o == nil || IsNil(o.Reference) {
		var ret string
		return ret
	}
	return *o.Reference
}

// GetReferenceOk returns a tuple with the Reference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1Order) GetReferenceOk() (*string, bool) {
	if o == nil || IsNil(o.Reference) {
		return nil, false
	}
	return o.Reference, true
}

// HasReference returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1Order) HasReference() bool {
	if o != nil && !IsNil(o.Reference) {
		return true
	}

	return false
}

// SetReference gets a reference to the given string and assigns it to the Reference field.
func (o *SodacardsDevpublicV1Order) SetReference(v string) {
	o.Reference = &v
}

// GetLines returns the Lines field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1Order) GetLines() []SodacardsDevpublicV1OrderItem {
	if o == nil || IsNil(o.Lines) {
		var ret []SodacardsDevpublicV1OrderItem
		return ret
	}
	return o.Lines
}

// GetLinesOk returns a tuple with the Lines field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1Order) GetLinesOk() ([]SodacardsDevpublicV1OrderItem, bool) {
	if o == nil || IsNil(o.Lines) {
		return nil, false
	}
	return o.Lines, true
}

// HasLines returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1Order) HasLines() bool {
	if o != nil && !IsNil(o.Lines) {
		return true
	}

	return false
}

// SetLines gets a reference to the given []SodacardsDevpublicV1OrderItem and assigns it to the Lines field.
func (o *SodacardsDevpublicV1Order) SetLines(v []SodacardsDevpublicV1OrderItem) {
	o.Lines = v
}

func (o SodacardsDevpublicV1Order) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SodacardsDevpublicV1Order) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.Reference) {
		toSerialize["reference"] = o.Reference
	}
	if !IsNil(o.Lines) {
		toSerialize["lines"] = o.Lines
	}
	return toSerialize, nil
}

type NullableSodacardsDevpublicV1Order struct {
	value *SodacardsDevpublicV1Order
	isSet bool
}

func (v NullableSodacardsDevpublicV1Order) Get() *SodacardsDevpublicV1Order {
	return v.value
}

func (v *NullableSodacardsDevpublicV1Order) Set(val *SodacardsDevpublicV1Order) {
	v.value = val
	v.isSet = true
}

func (v NullableSodacardsDevpublicV1Order) IsSet() bool {
	return v.isSet
}

func (v *NullableSodacardsDevpublicV1Order) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSodacardsDevpublicV1Order(val *SodacardsDevpublicV1Order) *NullableSodacardsDevpublicV1Order {
	return &NullableSodacardsDevpublicV1Order{value: val, isSet: true}
}

func (v NullableSodacardsDevpublicV1Order) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSodacardsDevpublicV1Order) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


