/*
SODACARDS Developer API

Sell gift cards and game top-ups from your own systems.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sodacards

import (
	"encoding/json"
)

// checks if the SodacardsDevpublicV1RevealOrderCodesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SodacardsDevpublicV1RevealOrderCodesResponse{}

// SodacardsDevpublicV1RevealOrderCodesResponse struct for SodacardsDevpublicV1RevealOrderCodesResponse
type SodacardsDevpublicV1RevealOrderCodesResponse struct {
	// codes are the delivered codes of the order.
	Codes []SodacardsDevpublicV1RevealedCode `json:"codes,omitempty"`
}

// NewSodacardsDevpublicV1RevealOrderCodesResponse instantiates a new SodacardsDevpublicV1RevealOrderCodesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSodacardsDevpublicV1RevealOrderCodesResponse() *SodacardsDevpublicV1RevealOrderCodesResponse {
	this := SodacardsDevpublicV1RevealOrderCodesResponse{}
	return &this
}

// NewSodacardsDevpublicV1RevealOrderCodesResponseWithDefaults instantiates a new SodacardsDevpublicV1RevealOrderCodesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSodacardsDevpublicV1RevealOrderCodesResponseWithDefaults() *SodacardsDevpublicV1RevealOrderCodesResponse {
	this := SodacardsDevpublicV1RevealOrderCodesResponse{}
	return &this
}

// GetCodes returns the Codes field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1RevealOrderCodesResponse) GetCodes() []SodacardsDevpublicV1RevealedCode {
	if o == nil || IsNil(o.Codes) {
		var ret []SodacardsDevpublicV1RevealedCode
		return ret
	}
	return o.Codes
}

// GetCodesOk returns a tuple with the Codes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1RevealOrderCodesResponse) GetCodesOk() ([]SodacardsDevpublicV1RevealedCode, bool) {
	if o == nil || IsNil(o.Codes) {
		return nil, false
	}
	return o.Codes, true
}

// HasCodes returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1RevealOrderCodesResponse) HasCodes() bool {
	if o != nil && !IsNil(o.Codes) {
		return true
	}

	return false
}

// SetCodes gets a reference to the given []SodacardsDevpublicV1RevealedCode and assigns it to the Codes field.
func (o *SodacardsDevpublicV1RevealOrderCodesResponse) SetCodes(v []SodacardsDevpublicV1RevealedCode) {
	o.Codes = v
}

func (o SodacardsDevpublicV1RevealOrderCodesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SodacardsDevpublicV1RevealOrderCodesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Codes) {
		toSerialize["codes"] = o.Codes
	}
	return toSerialize, nil
}

type NullableSodacardsDevpublicV1RevealOrderCodesResponse struct {
	value *SodacardsDevpublicV1RevealOrderCodesResponse
	isSet bool
}

func (v NullableSodacardsDevpublicV1RevealOrderCodesResponse) Get() *SodacardsDevpublicV1RevealOrderCodesResponse {
	return v.value
}

func (v *NullableSodacardsDevpublicV1RevealOrderCodesResponse) Set(val *SodacardsDevpublicV1RevealOrderCodesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSodacardsDevpublicV1RevealOrderCodesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSodacardsDevpublicV1RevealOrderCodesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSodacardsDevpublicV1RevealOrderCodesResponse(val *SodacardsDevpublicV1RevealOrderCodesResponse) *NullableSodacardsDevpublicV1RevealOrderCodesResponse {
	return &NullableSodacardsDevpublicV1RevealOrderCodesResponse{value: val, isSet: true}
}

func (v NullableSodacardsDevpublicV1RevealOrderCodesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSodacardsDevpublicV1RevealOrderCodesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


