/*
SODACARDS Developer API

Sell gift cards and game top-ups from your own systems.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sodacards

import (
	"encoding/json"
)

// checks if the SodacardsDevpublicV1ListCatalogRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SodacardsDevpublicV1ListCatalogRequest{}

// SodacardsDevpublicV1ListCatalogRequest struct for SodacardsDevpublicV1ListCatalogRequest
type SodacardsDevpublicV1ListCatalogRequest struct {
	// limit is the maximum number of products to return (1..100). Zero applies the  default page size.
	Limit *int32 `json:"limit,omitempty"`
	// cursor is the next_cursor of the previous page. Empty for the first page.
	Cursor *string `json:"cursor,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SodacardsDevpublicV1ListCatalogRequest SodacardsDevpublicV1ListCatalogRequest

// NewSodacardsDevpublicV1ListCatalogRequest instantiates a new SodacardsDevpublicV1ListCatalogRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSodacardsDevpublicV1ListCatalogRequest() *SodacardsDevpublicV1ListCatalogRequest {
	this := SodacardsDevpublicV1ListCatalogRequest{}
	return &this
}

// NewSodacardsDevpublicV1ListCatalogRequestWithDefaults instantiates a new SodacardsDevpublicV1ListCatalogRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSodacardsDevpublicV1ListCatalogRequestWithDefaults() *SodacardsDevpublicV1ListCatalogRequest {
	this := SodacardsDevpublicV1ListCatalogRequest{}
	return &this
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1ListCatalogRequest) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1ListCatalogRequest) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1ListCatalogRequest) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *SodacardsDevpublicV1ListCatalogRequest) SetLimit(v int32) {
	o.Limit = &v
}

// GetCursor returns the Cursor field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1ListCatalogRequest) GetCursor() string {
	if o == nil || IsNil(o.Cursor) {
		var ret string
		return ret
	}
	return *o.Cursor
}

// GetCursorOk returns a tuple with the Cursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1ListCatalogRequest) GetCursorOk() (*string, bool) {
	if o == nil || IsNil(o.Cursor) {
		return nil, false
	}
	return o.Cursor, true
}

// HasCursor returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1ListCatalogRequest) HasCursor() bool {
	if o != nil && !IsNil(o.Cursor) {
		return true
	}

	return false
}

// SetCursor gets a reference to the given string and assigns it to the Cursor field.
func (o *SodacardsDevpublicV1ListCatalogRequest) SetCursor(v string) {
	o.Cursor = &v
}

func (o SodacardsDevpublicV1ListCatalogRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SodacardsDevpublicV1ListCatalogRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if !IsNil(o.Cursor) {
		toSerialize["cursor"] = o.Cursor
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SodacardsDevpublicV1ListCatalogRequest) UnmarshalJSON(data []byte) (err error) {
	varSodacardsDevpublicV1ListCatalogRequest := _SodacardsDevpublicV1ListCatalogRequest{}

	err = json.Unmarshal(data, &varSodacardsDevpublicV1ListCatalogRequest)

	if err != nil {
		return err
	}

	*o = SodacardsDevpublicV1ListCatalogRequest(varSodacardsDevpublicV1ListCatalogRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "limit")
		delete(additionalProperties, "cursor")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSodacardsDevpublicV1ListCatalogRequest struct {
	value *SodacardsDevpublicV1ListCatalogRequest
	isSet bool
}

func (v NullableSodacardsDevpublicV1ListCatalogRequest) Get() *SodacardsDevpublicV1ListCatalogRequest {
	return v.value
}

func (v *NullableSodacardsDevpublicV1ListCatalogRequest) Set(val *SodacardsDevpublicV1ListCatalogRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSodacardsDevpublicV1ListCatalogRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSodacardsDevpublicV1ListCatalogRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSodacardsDevpublicV1ListCatalogRequest(val *SodacardsDevpublicV1ListCatalogRequest) *NullableSodacardsDevpublicV1ListCatalogRequest {
	return &NullableSodacardsDevpublicV1ListCatalogRequest{value: val, isSet: true}
}

func (v NullableSodacardsDevpublicV1ListCatalogRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSodacardsDevpublicV1ListCatalogRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


