/*
SODACARDS Developer API

Sell gift cards and game top-ups from your own systems.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sodacards

import (
	"encoding/json"
)

// checks if the SodacardsDevpublicV1RevealedCode type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SodacardsDevpublicV1RevealedCode{}

// SodacardsDevpublicV1RevealedCode RevealedCode is one delivered code of an order.
type SodacardsDevpublicV1RevealedCode struct {
	// label names what the code is for (e.g. the product line).
	Label *string `json:"label,omitempty"`
	// code is the delivered value. Treat it as a secret: do not log it.
	Code *string `json:"code,omitempty"`
}

// NewSodacardsDevpublicV1RevealedCode instantiates a new SodacardsDevpublicV1RevealedCode object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSodacardsDevpublicV1RevealedCode() *SodacardsDevpublicV1RevealedCode {
	this := SodacardsDevpublicV1RevealedCode{}
	return &this
}

// NewSodacardsDevpublicV1RevealedCodeWithDefaults instantiates a new SodacardsDevpublicV1RevealedCode object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSodacardsDevpublicV1RevealedCodeWithDefaults() *SodacardsDevpublicV1RevealedCode {
	this := SodacardsDevpublicV1RevealedCode{}
	return &this
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1RevealedCode) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1RevealedCode) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1RevealedCode) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *SodacardsDevpublicV1RevealedCode) SetLabel(v string) {
	o.Label = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1RevealedCode) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1RevealedCode) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1RevealedCode) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *SodacardsDevpublicV1RevealedCode) SetCode(v string) {
	o.Code = &v
}

func (o SodacardsDevpublicV1RevealedCode) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SodacardsDevpublicV1RevealedCode) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	return toSerialize, nil
}

type NullableSodacardsDevpublicV1RevealedCode struct {
	value *SodacardsDevpublicV1RevealedCode
	isSet bool
}

func (v NullableSodacardsDevpublicV1RevealedCode) Get() *SodacardsDevpublicV1RevealedCode {
	return v.value
}

func (v *NullableSodacardsDevpublicV1RevealedCode) Set(val *SodacardsDevpublicV1RevealedCode) {
	v.value = val
	v.isSet = true
}

func (v NullableSodacardsDevpublicV1RevealedCode) IsSet() bool {
	return v.isSet
}

func (v *NullableSodacardsDevpublicV1RevealedCode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSodacardsDevpublicV1RevealedCode(val *SodacardsDevpublicV1RevealedCode) *NullableSodacardsDevpublicV1RevealedCode {
	return &NullableSodacardsDevpublicV1RevealedCode{value: val, isSet: true}
}

func (v NullableSodacardsDevpublicV1RevealedCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSodacardsDevpublicV1RevealedCode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


