/*
SODACARDS Developer API

Sell gift cards and game top-ups from your own systems.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sodacards

import (
	"encoding/json"
)

// checks if the SodacardsDevpublicV1OrderLineInputFieldsEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SodacardsDevpublicV1OrderLineInputFieldsEntry{}

// SodacardsDevpublicV1OrderLineInputFieldsEntry struct for SodacardsDevpublicV1OrderLineInputFieldsEntry
type SodacardsDevpublicV1OrderLineInputFieldsEntry struct {
	Key *string `json:"key,omitempty"`
	Value *string `json:"value,omitempty"`
}

// NewSodacardsDevpublicV1OrderLineInputFieldsEntry instantiates a new SodacardsDevpublicV1OrderLineInputFieldsEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSodacardsDevpublicV1OrderLineInputFieldsEntry() *SodacardsDevpublicV1OrderLineInputFieldsEntry {
	this := SodacardsDevpublicV1OrderLineInputFieldsEntry{}
	return &this
}

// NewSodacardsDevpublicV1OrderLineInputFieldsEntryWithDefaults instantiates a new SodacardsDevpublicV1OrderLineInputFieldsEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSodacardsDevpublicV1OrderLineInputFieldsEntryWithDefaults() *SodacardsDevpublicV1OrderLineInputFieldsEntry {
	this := SodacardsDevpublicV1OrderLineInputFieldsEntry{}
	return &this
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1OrderLineInputFieldsEntry) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1OrderLineInputFieldsEntry) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1OrderLineInputFieldsEntry) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *SodacardsDevpublicV1OrderLineInputFieldsEntry) SetKey(v string) {
	o.Key = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1OrderLineInputFieldsEntry) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1OrderLineInputFieldsEntry) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1OrderLineInputFieldsEntry) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *SodacardsDevpublicV1OrderLineInputFieldsEntry) SetValue(v string) {
	o.Value = &v
}

func (o SodacardsDevpublicV1OrderLineInputFieldsEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SodacardsDevpublicV1OrderLineInputFieldsEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableSodacardsDevpublicV1OrderLineInputFieldsEntry struct {
	value *SodacardsDevpublicV1OrderLineInputFieldsEntry
	isSet bool
}

func (v NullableSodacardsDevpublicV1OrderLineInputFieldsEntry) Get() *SodacardsDevpublicV1OrderLineInputFieldsEntry {
	return v.value
}

func (v *NullableSodacardsDevpublicV1OrderLineInputFieldsEntry) Set(val *SodacardsDevpublicV1OrderLineInputFieldsEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableSodacardsDevpublicV1OrderLineInputFieldsEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableSodacardsDevpublicV1OrderLineInputFieldsEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSodacardsDevpublicV1OrderLineInputFieldsEntry(val *SodacardsDevpublicV1OrderLineInputFieldsEntry) *NullableSodacardsDevpublicV1OrderLineInputFieldsEntry {
	return &NullableSodacardsDevpublicV1OrderLineInputFieldsEntry{value: val, isSet: true}
}

func (v NullableSodacardsDevpublicV1OrderLineInputFieldsEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSodacardsDevpublicV1OrderLineInputFieldsEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


