/*
SODACARDS Developer API

Sell gift cards and game top-ups from your own systems.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sodacards

import (
	"encoding/json"
)

// checks if the SodacardsDevpublicV1ProductFaceValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SodacardsDevpublicV1ProductFaceValue{}

// SodacardsDevpublicV1ProductFaceValue ProductFaceValue is the nominal value printed on a product. amount is a decimal  string (e.g. \"10.00\") so fractional face values are exact.
type SodacardsDevpublicV1ProductFaceValue struct {
	// amount is the face value as an exact decimal string, e.g. \"10.00\".
	Amount *string `json:"amount,omitempty"`
	// currency is the ISO-4217 code of the face value, e.g. \"USD\".
	Currency *string `json:"currency,omitempty"`
}

// NewSodacardsDevpublicV1ProductFaceValue instantiates a new SodacardsDevpublicV1ProductFaceValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSodacardsDevpublicV1ProductFaceValue() *SodacardsDevpublicV1ProductFaceValue {
	this := SodacardsDevpublicV1ProductFaceValue{}
	return &this
}

// NewSodacardsDevpublicV1ProductFaceValueWithDefaults instantiates a new SodacardsDevpublicV1ProductFaceValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSodacardsDevpublicV1ProductFaceValueWithDefaults() *SodacardsDevpublicV1ProductFaceValue {
	this := SodacardsDevpublicV1ProductFaceValue{}
	return &this
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1ProductFaceValue) GetAmount() string {
	if o == nil || IsNil(o.Amount) {
		var ret string
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1ProductFaceValue) GetAmountOk() (*string, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1ProductFaceValue) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given string and assigns it to the Amount field.
func (o *SodacardsDevpublicV1ProductFaceValue) SetAmount(v string) {
	o.Amount = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1ProductFaceValue) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1ProductFaceValue) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1ProductFaceValue) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *SodacardsDevpublicV1ProductFaceValue) SetCurrency(v string) {
	o.Currency = &v
}

func (o SodacardsDevpublicV1ProductFaceValue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SodacardsDevpublicV1ProductFaceValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	return toSerialize, nil
}

type NullableSodacardsDevpublicV1ProductFaceValue struct {
	value *SodacardsDevpublicV1ProductFaceValue
	isSet bool
}

func (v NullableSodacardsDevpublicV1ProductFaceValue) Get() *SodacardsDevpublicV1ProductFaceValue {
	return v.value
}

func (v *NullableSodacardsDevpublicV1ProductFaceValue) Set(val *SodacardsDevpublicV1ProductFaceValue) {
	v.value = val
	v.isSet = true
}

func (v NullableSodacardsDevpublicV1ProductFaceValue) IsSet() bool {
	return v.isSet
}

func (v *NullableSodacardsDevpublicV1ProductFaceValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSodacardsDevpublicV1ProductFaceValue(val *SodacardsDevpublicV1ProductFaceValue) *NullableSodacardsDevpublicV1ProductFaceValue {
	return &NullableSodacardsDevpublicV1ProductFaceValue{value: val, isSet: true}
}

func (v NullableSodacardsDevpublicV1ProductFaceValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSodacardsDevpublicV1ProductFaceValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


