/*
SODACARDS Developer API

Sell gift cards and game top-ups from your own systems.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sodacards

import (
	"encoding/json"
)

// checks if the SodacardsDevpublicV1GetProductResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SodacardsDevpublicV1GetProductResponse{}

// SodacardsDevpublicV1GetProductResponse struct for SodacardsDevpublicV1GetProductResponse
type SodacardsDevpublicV1GetProductResponse struct {
	// product is the requested product, priced for the reseller.
	Product *SodacardsDevpublicV1Product `json:"product,omitempty"`
}

// NewSodacardsDevpublicV1GetProductResponse instantiates a new SodacardsDevpublicV1GetProductResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSodacardsDevpublicV1GetProductResponse() *SodacardsDevpublicV1GetProductResponse {
	this := SodacardsDevpublicV1GetProductResponse{}
	return &this
}

// NewSodacardsDevpublicV1GetProductResponseWithDefaults instantiates a new SodacardsDevpublicV1GetProductResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSodacardsDevpublicV1GetProductResponseWithDefaults() *SodacardsDevpublicV1GetProductResponse {
	this := SodacardsDevpublicV1GetProductResponse{}
	return &this
}

// GetProduct returns the Product field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1GetProductResponse) GetProduct() SodacardsDevpublicV1Product {
	if o == nil || IsNil(o.Product) {
		var ret SodacardsDevpublicV1Product
		return ret
	}
	return *o.Product
}

// GetProductOk returns a tuple with the Product field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1GetProductResponse) GetProductOk() (*SodacardsDevpublicV1Product, bool) {
	if o == nil || IsNil(o.Product) {
		return nil, false
	}
	return o.Product, true
}

// HasProduct returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1GetProductResponse) HasProduct() bool {
	if o != nil && !IsNil(o.Product) {
		return true
	}

	return false
}

// SetProduct gets a reference to the given SodacardsDevpublicV1Product and assigns it to the Product field.
func (o *SodacardsDevpublicV1GetProductResponse) SetProduct(v SodacardsDevpublicV1Product) {
	o.Product = &v
}

func (o SodacardsDevpublicV1GetProductResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SodacardsDevpublicV1GetProductResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Product) {
		toSerialize["product"] = o.Product
	}
	return toSerialize, nil
}

type NullableSodacardsDevpublicV1GetProductResponse struct {
	value *SodacardsDevpublicV1GetProductResponse
	isSet bool
}

func (v NullableSodacardsDevpublicV1GetProductResponse) Get() *SodacardsDevpublicV1GetProductResponse {
	return v.value
}

func (v *NullableSodacardsDevpublicV1GetProductResponse) Set(val *SodacardsDevpublicV1GetProductResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSodacardsDevpublicV1GetProductResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSodacardsDevpublicV1GetProductResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSodacardsDevpublicV1GetProductResponse(val *SodacardsDevpublicV1GetProductResponse) *NullableSodacardsDevpublicV1GetProductResponse {
	return &NullableSodacardsDevpublicV1GetProductResponse{value: val, isSet: true}
}

func (v NullableSodacardsDevpublicV1GetProductResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSodacardsDevpublicV1GetProductResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


