/*
SODACARDS Developer API

Sell gift cards and game top-ups from your own systems.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sodacards

import (
	"encoding/json"
)

// checks if the SodacardsDevpublicV1Product type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SodacardsDevpublicV1Product{}

// SodacardsDevpublicV1Product Product is one sellable item in the reseller catalog. Its id is what an order  line references. It never carries the supplier cost or routing.
type SodacardsDevpublicV1Product struct {
	// id identifies the product; use it to place an order for this item.
	Id *string `json:"id,omitempty"`
	// name is the human-readable product name.
	Name *string `json:"name,omitempty"`
	// face_value is the nominal value printed on the item (e.g. a 10 USD card),  which may differ from the currency the reseller pays in.
	FaceValue *SodacardsDevpublicV1ProductFaceValue `json:"faceValue,omitempty"`
	// price is what the reseller pays, in the currency of Money. It is absent when the item is not  yet priced (listed but not purchasable).
	Price *SodacardsDevpublicV1Money `json:"price,omitempty"`
	// strike_price is an optional reference (pre-discount) price, in the currency of Money, for  display. Absent when there is none.
	StrikePrice *SodacardsDevpublicV1Money `json:"strikePrice,omitempty"`
	// bonus describes any extra value granted with the item, e.g. \"+10%\". Empty  when there is none.
	Bonus *string `json:"bonus,omitempty"`
	// min_quantity and max_quantity bound how many units an order line may buy.
	MinQuantity *int32 `json:"minQuantity,omitempty"`
	MaxQuantity *int32 `json:"maxQuantity,omitempty"`
	// purchasable is true when the item has a price and can be ordered now.
	Purchasable *bool `json:"purchasable,omitempty"`
	// input_fields are the purchase-form fields this product requires. Empty for a  gift card that needs nothing; present for a game top-up. Read them to learn  which values to submit on the order line (OrderLine.input_fields, keyed by  each field's key) and to validate them before placing the order.
	InputFields []SodacardsDevpublicV1InputFieldSpec `json:"inputFields,omitempty"`
}

// NewSodacardsDevpublicV1Product instantiates a new SodacardsDevpublicV1Product object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSodacardsDevpublicV1Product() *SodacardsDevpublicV1Product {
	this := SodacardsDevpublicV1Product{}
	return &this
}

// NewSodacardsDevpublicV1ProductWithDefaults instantiates a new SodacardsDevpublicV1Product object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSodacardsDevpublicV1ProductWithDefaults() *SodacardsDevpublicV1Product {
	this := SodacardsDevpublicV1Product{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1Product) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1Product) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1Product) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *SodacardsDevpublicV1Product) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1Product) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1Product) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1Product) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SodacardsDevpublicV1Product) SetName(v string) {
	o.Name = &v
}

// GetFaceValue returns the FaceValue field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1Product) GetFaceValue() SodacardsDevpublicV1ProductFaceValue {
	if o == nil || IsNil(o.FaceValue) {
		var ret SodacardsDevpublicV1ProductFaceValue
		return ret
	}
	return *o.FaceValue
}

// GetFaceValueOk returns a tuple with the FaceValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1Product) GetFaceValueOk() (*SodacardsDevpublicV1ProductFaceValue, bool) {
	if o == nil || IsNil(o.FaceValue) {
		return nil, false
	}
	return o.FaceValue, true
}

// HasFaceValue returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1Product) HasFaceValue() bool {
	if o != nil && !IsNil(o.FaceValue) {
		return true
	}

	return false
}

// SetFaceValue gets a reference to the given SodacardsDevpublicV1ProductFaceValue and assigns it to the FaceValue field.
func (o *SodacardsDevpublicV1Product) SetFaceValue(v SodacardsDevpublicV1ProductFaceValue) {
	o.FaceValue = &v
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1Product) GetPrice() SodacardsDevpublicV1Money {
	if o == nil || IsNil(o.Price) {
		var ret SodacardsDevpublicV1Money
		return ret
	}
	return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1Product) GetPriceOk() (*SodacardsDevpublicV1Money, bool) {
	if o == nil || IsNil(o.Price) {
		return nil, false
	}
	return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1Product) HasPrice() bool {
	if o != nil && !IsNil(o.Price) {
		return true
	}

	return false
}

// SetPrice gets a reference to the given SodacardsDevpublicV1Money and assigns it to the Price field.
func (o *SodacardsDevpublicV1Product) SetPrice(v SodacardsDevpublicV1Money) {
	o.Price = &v
}

// GetStrikePrice returns the StrikePrice field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1Product) GetStrikePrice() SodacardsDevpublicV1Money {
	if o == nil || IsNil(o.StrikePrice) {
		var ret SodacardsDevpublicV1Money
		return ret
	}
	return *o.StrikePrice
}

// GetStrikePriceOk returns a tuple with the StrikePrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1Product) GetStrikePriceOk() (*SodacardsDevpublicV1Money, bool) {
	if o == nil || IsNil(o.StrikePrice) {
		return nil, false
	}
	return o.StrikePrice, true
}

// HasStrikePrice returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1Product) HasStrikePrice() bool {
	if o != nil && !IsNil(o.StrikePrice) {
		return true
	}

	return false
}

// SetStrikePrice gets a reference to the given SodacardsDevpublicV1Money and assigns it to the StrikePrice field.
func (o *SodacardsDevpublicV1Product) SetStrikePrice(v SodacardsDevpublicV1Money) {
	o.StrikePrice = &v
}

// GetBonus returns the Bonus field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1Product) GetBonus() string {
	if o == nil || IsNil(o.Bonus) {
		var ret string
		return ret
	}
	return *o.Bonus
}

// GetBonusOk returns a tuple with the Bonus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1Product) GetBonusOk() (*string, bool) {
	if o == nil || IsNil(o.Bonus) {
		return nil, false
	}
	return o.Bonus, true
}

// HasBonus returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1Product) HasBonus() bool {
	if o != nil && !IsNil(o.Bonus) {
		return true
	}

	return false
}

// SetBonus gets a reference to the given string and assigns it to the Bonus field.
func (o *SodacardsDevpublicV1Product) SetBonus(v string) {
	o.Bonus = &v
}

// GetMinQuantity returns the MinQuantity field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1Product) GetMinQuantity() int32 {
	if o == nil || IsNil(o.MinQuantity) {
		var ret int32
		return ret
	}
	return *o.MinQuantity
}

// GetMinQuantityOk returns a tuple with the MinQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1Product) GetMinQuantityOk() (*int32, bool) {
	if o == nil || IsNil(o.MinQuantity) {
		return nil, false
	}
	return o.MinQuantity, true
}

// HasMinQuantity returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1Product) HasMinQuantity() bool {
	if o != nil && !IsNil(o.MinQuantity) {
		return true
	}

	return false
}

// SetMinQuantity gets a reference to the given int32 and assigns it to the MinQuantity field.
func (o *SodacardsDevpublicV1Product) SetMinQuantity(v int32) {
	o.MinQuantity = &v
}

// GetMaxQuantity returns the MaxQuantity field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1Product) GetMaxQuantity() int32 {
	if o == nil || IsNil(o.MaxQuantity) {
		var ret int32
		return ret
	}
	return *o.MaxQuantity
}

// GetMaxQuantityOk returns a tuple with the MaxQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1Product) GetMaxQuantityOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxQuantity) {
		return nil, false
	}
	return o.MaxQuantity, true
}

// HasMaxQuantity returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1Product) HasMaxQuantity() bool {
	if o != nil && !IsNil(o.MaxQuantity) {
		return true
	}

	return false
}

// SetMaxQuantity gets a reference to the given int32 and assigns it to the MaxQuantity field.
func (o *SodacardsDevpublicV1Product) SetMaxQuantity(v int32) {
	o.MaxQuantity = &v
}

// GetPurchasable returns the Purchasable field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1Product) GetPurchasable() bool {
	if o == nil || IsNil(o.Purchasable) {
		var ret bool
		return ret
	}
	return *o.Purchasable
}

// GetPurchasableOk returns a tuple with the Purchasable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1Product) GetPurchasableOk() (*bool, bool) {
	if o == nil || IsNil(o.Purchasable) {
		return nil, false
	}
	return o.Purchasable, true
}

// HasPurchasable returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1Product) HasPurchasable() bool {
	if o != nil && !IsNil(o.Purchasable) {
		return true
	}

	return false
}

// SetPurchasable gets a reference to the given bool and assigns it to the Purchasable field.
func (o *SodacardsDevpublicV1Product) SetPurchasable(v bool) {
	o.Purchasable = &v
}

// GetInputFields returns the InputFields field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1Product) GetInputFields() []SodacardsDevpublicV1InputFieldSpec {
	if o == nil || IsNil(o.InputFields) {
		var ret []SodacardsDevpublicV1InputFieldSpec
		return ret
	}
	return o.InputFields
}

// GetInputFieldsOk returns a tuple with the InputFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1Product) GetInputFieldsOk() ([]SodacardsDevpublicV1InputFieldSpec, bool) {
	if o == nil || IsNil(o.InputFields) {
		return nil, false
	}
	return o.InputFields, true
}

// HasInputFields returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1Product) HasInputFields() bool {
	if o != nil && !IsNil(o.InputFields) {
		return true
	}

	return false
}

// SetInputFields gets a reference to the given []SodacardsDevpublicV1InputFieldSpec and assigns it to the InputFields field.
func (o *SodacardsDevpublicV1Product) SetInputFields(v []SodacardsDevpublicV1InputFieldSpec) {
	o.InputFields = v
}

func (o SodacardsDevpublicV1Product) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SodacardsDevpublicV1Product) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.FaceValue) {
		toSerialize["faceValue"] = o.FaceValue
	}
	if !IsNil(o.Price) {
		toSerialize["price"] = o.Price
	}
	if !IsNil(o.StrikePrice) {
		toSerialize["strikePrice"] = o.StrikePrice
	}
	if !IsNil(o.Bonus) {
		toSerialize["bonus"] = o.Bonus
	}
	if !IsNil(o.MinQuantity) {
		toSerialize["minQuantity"] = o.MinQuantity
	}
	if !IsNil(o.MaxQuantity) {
		toSerialize["maxQuantity"] = o.MaxQuantity
	}
	if !IsNil(o.Purchasable) {
		toSerialize["purchasable"] = o.Purchasable
	}
	if !IsNil(o.InputFields) {
		toSerialize["inputFields"] = o.InputFields
	}
	return toSerialize, nil
}

type NullableSodacardsDevpublicV1Product struct {
	value *SodacardsDevpublicV1Product
	isSet bool
}

func (v NullableSodacardsDevpublicV1Product) Get() *SodacardsDevpublicV1Product {
	return v.value
}

func (v *NullableSodacardsDevpublicV1Product) Set(val *SodacardsDevpublicV1Product) {
	v.value = val
	v.isSet = true
}

func (v NullableSodacardsDevpublicV1Product) IsSet() bool {
	return v.isSet
}

func (v *NullableSodacardsDevpublicV1Product) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSodacardsDevpublicV1Product(val *SodacardsDevpublicV1Product) *NullableSodacardsDevpublicV1Product {
	return &NullableSodacardsDevpublicV1Product{value: val, isSet: true}
}

func (v NullableSodacardsDevpublicV1Product) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSodacardsDevpublicV1Product) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


