/*
SODACARDS Developer API

Sell gift cards and game top-ups from your own systems.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sodacards

import (
	"encoding/json"
)

// checks if the SodacardsDevpublicV1RegisterWebhookResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SodacardsDevpublicV1RegisterWebhookResponse{}

// SodacardsDevpublicV1RegisterWebhookResponse struct for SodacardsDevpublicV1RegisterWebhookResponse
type SodacardsDevpublicV1RegisterWebhookResponse struct {
	// webhook is the registered endpoint.
	Webhook *SodacardsDevpublicV1Webhook `json:"webhook,omitempty"`
	// secret is the signing secret, shown only once. Store it; verify each delivery  with it. It is never returned again.
	Secret *string `json:"secret,omitempty"`
}

// NewSodacardsDevpublicV1RegisterWebhookResponse instantiates a new SodacardsDevpublicV1RegisterWebhookResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSodacardsDevpublicV1RegisterWebhookResponse() *SodacardsDevpublicV1RegisterWebhookResponse {
	this := SodacardsDevpublicV1RegisterWebhookResponse{}
	return &this
}

// NewSodacardsDevpublicV1RegisterWebhookResponseWithDefaults instantiates a new SodacardsDevpublicV1RegisterWebhookResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSodacardsDevpublicV1RegisterWebhookResponseWithDefaults() *SodacardsDevpublicV1RegisterWebhookResponse {
	this := SodacardsDevpublicV1RegisterWebhookResponse{}
	return &this
}

// GetWebhook returns the Webhook field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1RegisterWebhookResponse) GetWebhook() SodacardsDevpublicV1Webhook {
	if o == nil || IsNil(o.Webhook) {
		var ret SodacardsDevpublicV1Webhook
		return ret
	}
	return *o.Webhook
}

// GetWebhookOk returns a tuple with the Webhook field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1RegisterWebhookResponse) GetWebhookOk() (*SodacardsDevpublicV1Webhook, bool) {
	if o == nil || IsNil(o.Webhook) {
		return nil, false
	}
	return o.Webhook, true
}

// HasWebhook returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1RegisterWebhookResponse) HasWebhook() bool {
	if o != nil && !IsNil(o.Webhook) {
		return true
	}

	return false
}

// SetWebhook gets a reference to the given SodacardsDevpublicV1Webhook and assigns it to the Webhook field.
func (o *SodacardsDevpublicV1RegisterWebhookResponse) SetWebhook(v SodacardsDevpublicV1Webhook) {
	o.Webhook = &v
}

// GetSecret returns the Secret field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1RegisterWebhookResponse) GetSecret() string {
	if o == nil || IsNil(o.Secret) {
		var ret string
		return ret
	}
	return *o.Secret
}

// GetSecretOk returns a tuple with the Secret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1RegisterWebhookResponse) GetSecretOk() (*string, bool) {
	if o == nil || IsNil(o.Secret) {
		return nil, false
	}
	return o.Secret, true
}

// HasSecret returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1RegisterWebhookResponse) HasSecret() bool {
	if o != nil && !IsNil(o.Secret) {
		return true
	}

	return false
}

// SetSecret gets a reference to the given string and assigns it to the Secret field.
func (o *SodacardsDevpublicV1RegisterWebhookResponse) SetSecret(v string) {
	o.Secret = &v
}

func (o SodacardsDevpublicV1RegisterWebhookResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SodacardsDevpublicV1RegisterWebhookResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Webhook) {
		toSerialize["webhook"] = o.Webhook
	}
	if !IsNil(o.Secret) {
		toSerialize["secret"] = o.Secret
	}
	return toSerialize, nil
}

type NullableSodacardsDevpublicV1RegisterWebhookResponse struct {
	value *SodacardsDevpublicV1RegisterWebhookResponse
	isSet bool
}

func (v NullableSodacardsDevpublicV1RegisterWebhookResponse) Get() *SodacardsDevpublicV1RegisterWebhookResponse {
	return v.value
}

func (v *NullableSodacardsDevpublicV1RegisterWebhookResponse) Set(val *SodacardsDevpublicV1RegisterWebhookResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSodacardsDevpublicV1RegisterWebhookResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSodacardsDevpublicV1RegisterWebhookResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSodacardsDevpublicV1RegisterWebhookResponse(val *SodacardsDevpublicV1RegisterWebhookResponse) *NullableSodacardsDevpublicV1RegisterWebhookResponse {
	return &NullableSodacardsDevpublicV1RegisterWebhookResponse{value: val, isSet: true}
}

func (v NullableSodacardsDevpublicV1RegisterWebhookResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSodacardsDevpublicV1RegisterWebhookResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


