/*
SODACARDS Developer API

Sell gift cards and game top-ups from your own systems.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sodacards

import (
	"encoding/json"
)

// checks if the SodacardsDevpublicV1PlaceOrderRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SodacardsDevpublicV1PlaceOrderRequest{}

// SodacardsDevpublicV1PlaceOrderRequest struct for SodacardsDevpublicV1PlaceOrderRequest
type SodacardsDevpublicV1PlaceOrderRequest struct {
	// lines are the products to buy and how many of each. At least one is required.
	Lines []SodacardsDevpublicV1OrderLine `json:"lines,omitempty"`
	// reference is an optional identifier you attach to the order to correlate it  with your own system and look it up later. Reusing an Idempotency-Key with a  different reference is a conflict.
	Reference *string `json:"reference,omitempty"`
}

// NewSodacardsDevpublicV1PlaceOrderRequest instantiates a new SodacardsDevpublicV1PlaceOrderRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSodacardsDevpublicV1PlaceOrderRequest() *SodacardsDevpublicV1PlaceOrderRequest {
	this := SodacardsDevpublicV1PlaceOrderRequest{}
	return &this
}

// NewSodacardsDevpublicV1PlaceOrderRequestWithDefaults instantiates a new SodacardsDevpublicV1PlaceOrderRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSodacardsDevpublicV1PlaceOrderRequestWithDefaults() *SodacardsDevpublicV1PlaceOrderRequest {
	this := SodacardsDevpublicV1PlaceOrderRequest{}
	return &this
}

// GetLines returns the Lines field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1PlaceOrderRequest) GetLines() []SodacardsDevpublicV1OrderLine {
	if o == nil || IsNil(o.Lines) {
		var ret []SodacardsDevpublicV1OrderLine
		return ret
	}
	return o.Lines
}

// GetLinesOk returns a tuple with the Lines field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1PlaceOrderRequest) GetLinesOk() ([]SodacardsDevpublicV1OrderLine, bool) {
	if o == nil || IsNil(o.Lines) {
		return nil, false
	}
	return o.Lines, true
}

// HasLines returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1PlaceOrderRequest) HasLines() bool {
	if o != nil && !IsNil(o.Lines) {
		return true
	}

	return false
}

// SetLines gets a reference to the given []SodacardsDevpublicV1OrderLine and assigns it to the Lines field.
func (o *SodacardsDevpublicV1PlaceOrderRequest) SetLines(v []SodacardsDevpublicV1OrderLine) {
	o.Lines = v
}

// GetReference returns the Reference field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1PlaceOrderRequest) GetReference() string {
	if o == nil || IsNil(o.Reference) {
		var ret string
		return ret
	}
	return *o.Reference
}

// GetReferenceOk returns a tuple with the Reference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1PlaceOrderRequest) GetReferenceOk() (*string, bool) {
	if o == nil || IsNil(o.Reference) {
		return nil, false
	}
	return o.Reference, true
}

// HasReference returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1PlaceOrderRequest) HasReference() bool {
	if o != nil && !IsNil(o.Reference) {
		return true
	}

	return false
}

// SetReference gets a reference to the given string and assigns it to the Reference field.
func (o *SodacardsDevpublicV1PlaceOrderRequest) SetReference(v string) {
	o.Reference = &v
}

func (o SodacardsDevpublicV1PlaceOrderRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SodacardsDevpublicV1PlaceOrderRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Lines) {
		toSerialize["lines"] = o.Lines
	}
	if !IsNil(o.Reference) {
		toSerialize["reference"] = o.Reference
	}
	return toSerialize, nil
}

type NullableSodacardsDevpublicV1PlaceOrderRequest struct {
	value *SodacardsDevpublicV1PlaceOrderRequest
	isSet bool
}

func (v NullableSodacardsDevpublicV1PlaceOrderRequest) Get() *SodacardsDevpublicV1PlaceOrderRequest {
	return v.value
}

func (v *NullableSodacardsDevpublicV1PlaceOrderRequest) Set(val *SodacardsDevpublicV1PlaceOrderRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSodacardsDevpublicV1PlaceOrderRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSodacardsDevpublicV1PlaceOrderRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSodacardsDevpublicV1PlaceOrderRequest(val *SodacardsDevpublicV1PlaceOrderRequest) *NullableSodacardsDevpublicV1PlaceOrderRequest {
	return &NullableSodacardsDevpublicV1PlaceOrderRequest{value: val, isSet: true}
}

func (v NullableSodacardsDevpublicV1PlaceOrderRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSodacardsDevpublicV1PlaceOrderRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


