/*
SODACARDS Developer API

Sell gift cards and game top-ups from your own systems.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sodacards

import (
	"encoding/json"
)

// checks if the SodacardsDevpublicV1GetProductRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SodacardsDevpublicV1GetProductRequest{}

// SodacardsDevpublicV1GetProductRequest struct for SodacardsDevpublicV1GetProductRequest
type SodacardsDevpublicV1GetProductRequest struct {
	// id is the product id, taken from a catalog entry.
	Id *string `json:"id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SodacardsDevpublicV1GetProductRequest SodacardsDevpublicV1GetProductRequest

// NewSodacardsDevpublicV1GetProductRequest instantiates a new SodacardsDevpublicV1GetProductRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSodacardsDevpublicV1GetProductRequest() *SodacardsDevpublicV1GetProductRequest {
	this := SodacardsDevpublicV1GetProductRequest{}
	return &this
}

// NewSodacardsDevpublicV1GetProductRequestWithDefaults instantiates a new SodacardsDevpublicV1GetProductRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSodacardsDevpublicV1GetProductRequestWithDefaults() *SodacardsDevpublicV1GetProductRequest {
	this := SodacardsDevpublicV1GetProductRequest{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1GetProductRequest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1GetProductRequest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1GetProductRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *SodacardsDevpublicV1GetProductRequest) SetId(v string) {
	o.Id = &v
}

func (o SodacardsDevpublicV1GetProductRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SodacardsDevpublicV1GetProductRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SodacardsDevpublicV1GetProductRequest) UnmarshalJSON(data []byte) (err error) {
	varSodacardsDevpublicV1GetProductRequest := _SodacardsDevpublicV1GetProductRequest{}

	err = json.Unmarshal(data, &varSodacardsDevpublicV1GetProductRequest)

	if err != nil {
		return err
	}

	*o = SodacardsDevpublicV1GetProductRequest(varSodacardsDevpublicV1GetProductRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSodacardsDevpublicV1GetProductRequest struct {
	value *SodacardsDevpublicV1GetProductRequest
	isSet bool
}

func (v NullableSodacardsDevpublicV1GetProductRequest) Get() *SodacardsDevpublicV1GetProductRequest {
	return v.value
}

func (v *NullableSodacardsDevpublicV1GetProductRequest) Set(val *SodacardsDevpublicV1GetProductRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSodacardsDevpublicV1GetProductRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSodacardsDevpublicV1GetProductRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSodacardsDevpublicV1GetProductRequest(val *SodacardsDevpublicV1GetProductRequest) *NullableSodacardsDevpublicV1GetProductRequest {
	return &NullableSodacardsDevpublicV1GetProductRequest{value: val, isSet: true}
}

func (v NullableSodacardsDevpublicV1GetProductRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSodacardsDevpublicV1GetProductRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


