/*
SODACARDS Developer API

Sell gift cards and game top-ups from your own systems.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sodacards

import (
	"encoding/json"
)

// checks if the SodacardsDevpublicV1RevealOrderCodesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SodacardsDevpublicV1RevealOrderCodesRequest{}

// SodacardsDevpublicV1RevealOrderCodesRequest struct for SodacardsDevpublicV1RevealOrderCodesRequest
type SodacardsDevpublicV1RevealOrderCodesRequest struct {
	// order_id is the order whose codes to reveal.
	OrderId *string `json:"orderId,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SodacardsDevpublicV1RevealOrderCodesRequest SodacardsDevpublicV1RevealOrderCodesRequest

// NewSodacardsDevpublicV1RevealOrderCodesRequest instantiates a new SodacardsDevpublicV1RevealOrderCodesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSodacardsDevpublicV1RevealOrderCodesRequest() *SodacardsDevpublicV1RevealOrderCodesRequest {
	this := SodacardsDevpublicV1RevealOrderCodesRequest{}
	return &this
}

// NewSodacardsDevpublicV1RevealOrderCodesRequestWithDefaults instantiates a new SodacardsDevpublicV1RevealOrderCodesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSodacardsDevpublicV1RevealOrderCodesRequestWithDefaults() *SodacardsDevpublicV1RevealOrderCodesRequest {
	this := SodacardsDevpublicV1RevealOrderCodesRequest{}
	return &this
}

// GetOrderId returns the OrderId field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1RevealOrderCodesRequest) GetOrderId() string {
	if o == nil || IsNil(o.OrderId) {
		var ret string
		return ret
	}
	return *o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1RevealOrderCodesRequest) GetOrderIdOk() (*string, bool) {
	if o == nil || IsNil(o.OrderId) {
		return nil, false
	}
	return o.OrderId, true
}

// HasOrderId returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1RevealOrderCodesRequest) HasOrderId() bool {
	if o != nil && !IsNil(o.OrderId) {
		return true
	}

	return false
}

// SetOrderId gets a reference to the given string and assigns it to the OrderId field.
func (o *SodacardsDevpublicV1RevealOrderCodesRequest) SetOrderId(v string) {
	o.OrderId = &v
}

func (o SodacardsDevpublicV1RevealOrderCodesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SodacardsDevpublicV1RevealOrderCodesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OrderId) {
		toSerialize["orderId"] = o.OrderId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SodacardsDevpublicV1RevealOrderCodesRequest) UnmarshalJSON(data []byte) (err error) {
	varSodacardsDevpublicV1RevealOrderCodesRequest := _SodacardsDevpublicV1RevealOrderCodesRequest{}

	err = json.Unmarshal(data, &varSodacardsDevpublicV1RevealOrderCodesRequest)

	if err != nil {
		return err
	}

	*o = SodacardsDevpublicV1RevealOrderCodesRequest(varSodacardsDevpublicV1RevealOrderCodesRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "orderId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSodacardsDevpublicV1RevealOrderCodesRequest struct {
	value *SodacardsDevpublicV1RevealOrderCodesRequest
	isSet bool
}

func (v NullableSodacardsDevpublicV1RevealOrderCodesRequest) Get() *SodacardsDevpublicV1RevealOrderCodesRequest {
	return v.value
}

func (v *NullableSodacardsDevpublicV1RevealOrderCodesRequest) Set(val *SodacardsDevpublicV1RevealOrderCodesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSodacardsDevpublicV1RevealOrderCodesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSodacardsDevpublicV1RevealOrderCodesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSodacardsDevpublicV1RevealOrderCodesRequest(val *SodacardsDevpublicV1RevealOrderCodesRequest) *NullableSodacardsDevpublicV1RevealOrderCodesRequest {
	return &NullableSodacardsDevpublicV1RevealOrderCodesRequest{value: val, isSet: true}
}

func (v NullableSodacardsDevpublicV1RevealOrderCodesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSodacardsDevpublicV1RevealOrderCodesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


