/*
SODACARDS Developer API

Sell gift cards and game top-ups from your own systems.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sodacards

import (
	"encoding/json"
)

// checks if the SodacardsDevpublicV1PlacedOrder type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SodacardsDevpublicV1PlacedOrder{}

// SodacardsDevpublicV1PlacedOrder PlacedOrder is the accepted order: its id, the amount charged to the wallet  (see total), and its current status.
type SodacardsDevpublicV1PlacedOrder struct {
	// id identifies the order; use it to poll the order and reveal its codes.
	Id *string `json:"id,omitempty"`
	// status is the order's current state, e.g. \"pending\", \"processing\",  \"completed\", \"partially_completed\", \"failed\" or \"refunded\".
	Status *string `json:"status,omitempty"`
	// total is the amount charged to the reseller's wallet, in the currency of Money.
	Total *SodacardsDevpublicV1Money `json:"total,omitempty"`
}

// NewSodacardsDevpublicV1PlacedOrder instantiates a new SodacardsDevpublicV1PlacedOrder object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSodacardsDevpublicV1PlacedOrder() *SodacardsDevpublicV1PlacedOrder {
	this := SodacardsDevpublicV1PlacedOrder{}
	return &this
}

// NewSodacardsDevpublicV1PlacedOrderWithDefaults instantiates a new SodacardsDevpublicV1PlacedOrder object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSodacardsDevpublicV1PlacedOrderWithDefaults() *SodacardsDevpublicV1PlacedOrder {
	this := SodacardsDevpublicV1PlacedOrder{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1PlacedOrder) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1PlacedOrder) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1PlacedOrder) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *SodacardsDevpublicV1PlacedOrder) SetId(v string) {
	o.Id = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1PlacedOrder) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1PlacedOrder) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1PlacedOrder) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *SodacardsDevpublicV1PlacedOrder) SetStatus(v string) {
	o.Status = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1PlacedOrder) GetTotal() SodacardsDevpublicV1Money {
	if o == nil || IsNil(o.Total) {
		var ret SodacardsDevpublicV1Money
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1PlacedOrder) GetTotalOk() (*SodacardsDevpublicV1Money, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1PlacedOrder) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given SodacardsDevpublicV1Money and assigns it to the Total field.
func (o *SodacardsDevpublicV1PlacedOrder) SetTotal(v SodacardsDevpublicV1Money) {
	o.Total = &v
}

func (o SodacardsDevpublicV1PlacedOrder) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SodacardsDevpublicV1PlacedOrder) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullableSodacardsDevpublicV1PlacedOrder struct {
	value *SodacardsDevpublicV1PlacedOrder
	isSet bool
}

func (v NullableSodacardsDevpublicV1PlacedOrder) Get() *SodacardsDevpublicV1PlacedOrder {
	return v.value
}

func (v *NullableSodacardsDevpublicV1PlacedOrder) Set(val *SodacardsDevpublicV1PlacedOrder) {
	v.value = val
	v.isSet = true
}

func (v NullableSodacardsDevpublicV1PlacedOrder) IsSet() bool {
	return v.isSet
}

func (v *NullableSodacardsDevpublicV1PlacedOrder) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSodacardsDevpublicV1PlacedOrder(val *SodacardsDevpublicV1PlacedOrder) *NullableSodacardsDevpublicV1PlacedOrder {
	return &NullableSodacardsDevpublicV1PlacedOrder{value: val, isSet: true}
}

func (v NullableSodacardsDevpublicV1PlacedOrder) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSodacardsDevpublicV1PlacedOrder) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


