/*
SODACARDS Developer API

Sell gift cards and game top-ups from your own systems.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sodacards

import (
	"encoding/json"
)

// checks if the SodacardsDevpublicV1PlaceOrderResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SodacardsDevpublicV1PlaceOrderResponse{}

// SodacardsDevpublicV1PlaceOrderResponse struct for SodacardsDevpublicV1PlaceOrderResponse
type SodacardsDevpublicV1PlaceOrderResponse struct {
	// order is the accepted order. It is settled from the wallet at placement, so it  is born already paid: its status is \"processing\" while it is being fulfilled,  or \"completed\" when fulfillment is immediate. It is never \"pending\" -- the  developer API charges synchronously, so an order awaiting payment is not a  state it produces. Poll the order to follow it to \"completed\".
	Order *SodacardsDevpublicV1PlacedOrder `json:"order,omitempty"`
}

// NewSodacardsDevpublicV1PlaceOrderResponse instantiates a new SodacardsDevpublicV1PlaceOrderResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSodacardsDevpublicV1PlaceOrderResponse() *SodacardsDevpublicV1PlaceOrderResponse {
	this := SodacardsDevpublicV1PlaceOrderResponse{}
	return &this
}

// NewSodacardsDevpublicV1PlaceOrderResponseWithDefaults instantiates a new SodacardsDevpublicV1PlaceOrderResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSodacardsDevpublicV1PlaceOrderResponseWithDefaults() *SodacardsDevpublicV1PlaceOrderResponse {
	this := SodacardsDevpublicV1PlaceOrderResponse{}
	return &this
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1PlaceOrderResponse) GetOrder() SodacardsDevpublicV1PlacedOrder {
	if o == nil || IsNil(o.Order) {
		var ret SodacardsDevpublicV1PlacedOrder
		return ret
	}
	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1PlaceOrderResponse) GetOrderOk() (*SodacardsDevpublicV1PlacedOrder, bool) {
	if o == nil || IsNil(o.Order) {
		return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1PlaceOrderResponse) HasOrder() bool {
	if o != nil && !IsNil(o.Order) {
		return true
	}

	return false
}

// SetOrder gets a reference to the given SodacardsDevpublicV1PlacedOrder and assigns it to the Order field.
func (o *SodacardsDevpublicV1PlaceOrderResponse) SetOrder(v SodacardsDevpublicV1PlacedOrder) {
	o.Order = &v
}

func (o SodacardsDevpublicV1PlaceOrderResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SodacardsDevpublicV1PlaceOrderResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Order) {
		toSerialize["order"] = o.Order
	}
	return toSerialize, nil
}

type NullableSodacardsDevpublicV1PlaceOrderResponse struct {
	value *SodacardsDevpublicV1PlaceOrderResponse
	isSet bool
}

func (v NullableSodacardsDevpublicV1PlaceOrderResponse) Get() *SodacardsDevpublicV1PlaceOrderResponse {
	return v.value
}

func (v *NullableSodacardsDevpublicV1PlaceOrderResponse) Set(val *SodacardsDevpublicV1PlaceOrderResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSodacardsDevpublicV1PlaceOrderResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSodacardsDevpublicV1PlaceOrderResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSodacardsDevpublicV1PlaceOrderResponse(val *SodacardsDevpublicV1PlaceOrderResponse) *NullableSodacardsDevpublicV1PlaceOrderResponse {
	return &NullableSodacardsDevpublicV1PlaceOrderResponse{value: val, isSet: true}
}

func (v NullableSodacardsDevpublicV1PlaceOrderResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSodacardsDevpublicV1PlaceOrderResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


