/*
SODACARDS Developer API

Sell gift cards and game top-ups from your own systems.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sodacards

import (
	"encoding/json"
)

// checks if the SodacardsDevpublicV1ListCatalogResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SodacardsDevpublicV1ListCatalogResponse{}

// SodacardsDevpublicV1ListCatalogResponse struct for SodacardsDevpublicV1ListCatalogResponse
type SodacardsDevpublicV1ListCatalogResponse struct {
	// data is the page of products, priced for the calling reseller.
	Data []SodacardsDevpublicV1Product `json:"data,omitempty"`
	// has_more is true when another page follows this one.
	HasMore *bool `json:"hasMore,omitempty"`
	// next_cursor fetches the next page. Empty on the last page.
	NextCursor *string `json:"nextCursor,omitempty"`
}

// NewSodacardsDevpublicV1ListCatalogResponse instantiates a new SodacardsDevpublicV1ListCatalogResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSodacardsDevpublicV1ListCatalogResponse() *SodacardsDevpublicV1ListCatalogResponse {
	this := SodacardsDevpublicV1ListCatalogResponse{}
	return &this
}

// NewSodacardsDevpublicV1ListCatalogResponseWithDefaults instantiates a new SodacardsDevpublicV1ListCatalogResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSodacardsDevpublicV1ListCatalogResponseWithDefaults() *SodacardsDevpublicV1ListCatalogResponse {
	this := SodacardsDevpublicV1ListCatalogResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1ListCatalogResponse) GetData() []SodacardsDevpublicV1Product {
	if o == nil || IsNil(o.Data) {
		var ret []SodacardsDevpublicV1Product
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1ListCatalogResponse) GetDataOk() ([]SodacardsDevpublicV1Product, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1ListCatalogResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []SodacardsDevpublicV1Product and assigns it to the Data field.
func (o *SodacardsDevpublicV1ListCatalogResponse) SetData(v []SodacardsDevpublicV1Product) {
	o.Data = v
}

// GetHasMore returns the HasMore field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1ListCatalogResponse) GetHasMore() bool {
	if o == nil || IsNil(o.HasMore) {
		var ret bool
		return ret
	}
	return *o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1ListCatalogResponse) GetHasMoreOk() (*bool, bool) {
	if o == nil || IsNil(o.HasMore) {
		return nil, false
	}
	return o.HasMore, true
}

// HasHasMore returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1ListCatalogResponse) HasHasMore() bool {
	if o != nil && !IsNil(o.HasMore) {
		return true
	}

	return false
}

// SetHasMore gets a reference to the given bool and assigns it to the HasMore field.
func (o *SodacardsDevpublicV1ListCatalogResponse) SetHasMore(v bool) {
	o.HasMore = &v
}

// GetNextCursor returns the NextCursor field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1ListCatalogResponse) GetNextCursor() string {
	if o == nil || IsNil(o.NextCursor) {
		var ret string
		return ret
	}
	return *o.NextCursor
}

// GetNextCursorOk returns a tuple with the NextCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1ListCatalogResponse) GetNextCursorOk() (*string, bool) {
	if o == nil || IsNil(o.NextCursor) {
		return nil, false
	}
	return o.NextCursor, true
}

// HasNextCursor returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1ListCatalogResponse) HasNextCursor() bool {
	if o != nil && !IsNil(o.NextCursor) {
		return true
	}

	return false
}

// SetNextCursor gets a reference to the given string and assigns it to the NextCursor field.
func (o *SodacardsDevpublicV1ListCatalogResponse) SetNextCursor(v string) {
	o.NextCursor = &v
}

func (o SodacardsDevpublicV1ListCatalogResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SodacardsDevpublicV1ListCatalogResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.HasMore) {
		toSerialize["hasMore"] = o.HasMore
	}
	if !IsNil(o.NextCursor) {
		toSerialize["nextCursor"] = o.NextCursor
	}
	return toSerialize, nil
}

type NullableSodacardsDevpublicV1ListCatalogResponse struct {
	value *SodacardsDevpublicV1ListCatalogResponse
	isSet bool
}

func (v NullableSodacardsDevpublicV1ListCatalogResponse) Get() *SodacardsDevpublicV1ListCatalogResponse {
	return v.value
}

func (v *NullableSodacardsDevpublicV1ListCatalogResponse) Set(val *SodacardsDevpublicV1ListCatalogResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSodacardsDevpublicV1ListCatalogResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSodacardsDevpublicV1ListCatalogResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSodacardsDevpublicV1ListCatalogResponse(val *SodacardsDevpublicV1ListCatalogResponse) *NullableSodacardsDevpublicV1ListCatalogResponse {
	return &NullableSodacardsDevpublicV1ListCatalogResponse{value: val, isSet: true}
}

func (v NullableSodacardsDevpublicV1ListCatalogResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSodacardsDevpublicV1ListCatalogResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


