/*
SODACARDS Developer API

Sell gift cards and game top-ups from your own systems.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sodacards

import (
	"encoding/json"
)

// checks if the SodacardsDevpublicV1GetOrderRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SodacardsDevpublicV1GetOrderRequest{}

// SodacardsDevpublicV1GetOrderRequest struct for SodacardsDevpublicV1GetOrderRequest
type SodacardsDevpublicV1GetOrderRequest struct {
	// id is the order id, from PlaceOrder.
	Id *string `json:"id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SodacardsDevpublicV1GetOrderRequest SodacardsDevpublicV1GetOrderRequest

// NewSodacardsDevpublicV1GetOrderRequest instantiates a new SodacardsDevpublicV1GetOrderRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSodacardsDevpublicV1GetOrderRequest() *SodacardsDevpublicV1GetOrderRequest {
	this := SodacardsDevpublicV1GetOrderRequest{}
	return &this
}

// NewSodacardsDevpublicV1GetOrderRequestWithDefaults instantiates a new SodacardsDevpublicV1GetOrderRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSodacardsDevpublicV1GetOrderRequestWithDefaults() *SodacardsDevpublicV1GetOrderRequest {
	this := SodacardsDevpublicV1GetOrderRequest{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1GetOrderRequest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1GetOrderRequest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1GetOrderRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *SodacardsDevpublicV1GetOrderRequest) SetId(v string) {
	o.Id = &v
}

func (o SodacardsDevpublicV1GetOrderRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SodacardsDevpublicV1GetOrderRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SodacardsDevpublicV1GetOrderRequest) UnmarshalJSON(data []byte) (err error) {
	varSodacardsDevpublicV1GetOrderRequest := _SodacardsDevpublicV1GetOrderRequest{}

	err = json.Unmarshal(data, &varSodacardsDevpublicV1GetOrderRequest)

	if err != nil {
		return err
	}

	*o = SodacardsDevpublicV1GetOrderRequest(varSodacardsDevpublicV1GetOrderRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSodacardsDevpublicV1GetOrderRequest struct {
	value *SodacardsDevpublicV1GetOrderRequest
	isSet bool
}

func (v NullableSodacardsDevpublicV1GetOrderRequest) Get() *SodacardsDevpublicV1GetOrderRequest {
	return v.value
}

func (v *NullableSodacardsDevpublicV1GetOrderRequest) Set(val *SodacardsDevpublicV1GetOrderRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSodacardsDevpublicV1GetOrderRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSodacardsDevpublicV1GetOrderRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSodacardsDevpublicV1GetOrderRequest(val *SodacardsDevpublicV1GetOrderRequest) *NullableSodacardsDevpublicV1GetOrderRequest {
	return &NullableSodacardsDevpublicV1GetOrderRequest{value: val, isSet: true}
}

func (v NullableSodacardsDevpublicV1GetOrderRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSodacardsDevpublicV1GetOrderRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


