/*
SODACARDS Developer API

Sell gift cards and game top-ups from your own systems.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sodacards

import (
	"encoding/json"
)

// checks if the SodacardsDevpublicV1ListOrdersRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SodacardsDevpublicV1ListOrdersRequest{}

// SodacardsDevpublicV1ListOrdersRequest struct for SodacardsDevpublicV1ListOrdersRequest
type SodacardsDevpublicV1ListOrdersRequest struct {
	// limit is the maximum number of orders to return (1..100). Zero applies the  default page size.
	Limit *int32 `json:"limit,omitempty"`
	// cursor is the next_cursor of the previous page. Empty for the first page.
	Cursor *string `json:"cursor,omitempty"`
	// reference, when set, filters the list to the orders carrying that client  reference. The cursor is ignored when a reference is given.
	Reference *string `json:"reference,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SodacardsDevpublicV1ListOrdersRequest SodacardsDevpublicV1ListOrdersRequest

// NewSodacardsDevpublicV1ListOrdersRequest instantiates a new SodacardsDevpublicV1ListOrdersRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSodacardsDevpublicV1ListOrdersRequest() *SodacardsDevpublicV1ListOrdersRequest {
	this := SodacardsDevpublicV1ListOrdersRequest{}
	return &this
}

// NewSodacardsDevpublicV1ListOrdersRequestWithDefaults instantiates a new SodacardsDevpublicV1ListOrdersRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSodacardsDevpublicV1ListOrdersRequestWithDefaults() *SodacardsDevpublicV1ListOrdersRequest {
	this := SodacardsDevpublicV1ListOrdersRequest{}
	return &this
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1ListOrdersRequest) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1ListOrdersRequest) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1ListOrdersRequest) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *SodacardsDevpublicV1ListOrdersRequest) SetLimit(v int32) {
	o.Limit = &v
}

// GetCursor returns the Cursor field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1ListOrdersRequest) GetCursor() string {
	if o == nil || IsNil(o.Cursor) {
		var ret string
		return ret
	}
	return *o.Cursor
}

// GetCursorOk returns a tuple with the Cursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1ListOrdersRequest) GetCursorOk() (*string, bool) {
	if o == nil || IsNil(o.Cursor) {
		return nil, false
	}
	return o.Cursor, true
}

// HasCursor returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1ListOrdersRequest) HasCursor() bool {
	if o != nil && !IsNil(o.Cursor) {
		return true
	}

	return false
}

// SetCursor gets a reference to the given string and assigns it to the Cursor field.
func (o *SodacardsDevpublicV1ListOrdersRequest) SetCursor(v string) {
	o.Cursor = &v
}

// GetReference returns the Reference field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1ListOrdersRequest) GetReference() string {
	if o == nil || IsNil(o.Reference) {
		var ret string
		return ret
	}
	return *o.Reference
}

// GetReferenceOk returns a tuple with the Reference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1ListOrdersRequest) GetReferenceOk() (*string, bool) {
	if o == nil || IsNil(o.Reference) {
		return nil, false
	}
	return o.Reference, true
}

// HasReference returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1ListOrdersRequest) HasReference() bool {
	if o != nil && !IsNil(o.Reference) {
		return true
	}

	return false
}

// SetReference gets a reference to the given string and assigns it to the Reference field.
func (o *SodacardsDevpublicV1ListOrdersRequest) SetReference(v string) {
	o.Reference = &v
}

func (o SodacardsDevpublicV1ListOrdersRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SodacardsDevpublicV1ListOrdersRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if !IsNil(o.Cursor) {
		toSerialize["cursor"] = o.Cursor
	}
	if !IsNil(o.Reference) {
		toSerialize["reference"] = o.Reference
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SodacardsDevpublicV1ListOrdersRequest) UnmarshalJSON(data []byte) (err error) {
	varSodacardsDevpublicV1ListOrdersRequest := _SodacardsDevpublicV1ListOrdersRequest{}

	err = json.Unmarshal(data, &varSodacardsDevpublicV1ListOrdersRequest)

	if err != nil {
		return err
	}

	*o = SodacardsDevpublicV1ListOrdersRequest(varSodacardsDevpublicV1ListOrdersRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "limit")
		delete(additionalProperties, "cursor")
		delete(additionalProperties, "reference")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSodacardsDevpublicV1ListOrdersRequest struct {
	value *SodacardsDevpublicV1ListOrdersRequest
	isSet bool
}

func (v NullableSodacardsDevpublicV1ListOrdersRequest) Get() *SodacardsDevpublicV1ListOrdersRequest {
	return v.value
}

func (v *NullableSodacardsDevpublicV1ListOrdersRequest) Set(val *SodacardsDevpublicV1ListOrdersRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSodacardsDevpublicV1ListOrdersRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSodacardsDevpublicV1ListOrdersRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSodacardsDevpublicV1ListOrdersRequest(val *SodacardsDevpublicV1ListOrdersRequest) *NullableSodacardsDevpublicV1ListOrdersRequest {
	return &NullableSodacardsDevpublicV1ListOrdersRequest{value: val, isSet: true}
}

func (v NullableSodacardsDevpublicV1ListOrdersRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSodacardsDevpublicV1ListOrdersRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


