/*
SODACARDS Developer API

Sell gift cards and game top-ups from your own systems.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sodacards

import (
	"encoding/json"
)

// checks if the SodacardsDevpublicV1PingResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SodacardsDevpublicV1PingResponse{}

// SodacardsDevpublicV1PingResponse struct for SodacardsDevpublicV1PingResponse
type SodacardsDevpublicV1PingResponse struct {
	// status is \"ok\" when the key authenticated.
	Status *string `json:"status,omitempty"`
	// environment is \"live\" or \"test\", so a developer sees which mode their key is  in.
	Environment *string `json:"environment,omitempty"`
	// reseller_id is the account the key belongs to.
	ResellerId *string `json:"resellerId,omitempty"`
}

// NewSodacardsDevpublicV1PingResponse instantiates a new SodacardsDevpublicV1PingResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSodacardsDevpublicV1PingResponse() *SodacardsDevpublicV1PingResponse {
	this := SodacardsDevpublicV1PingResponse{}
	return &this
}

// NewSodacardsDevpublicV1PingResponseWithDefaults instantiates a new SodacardsDevpublicV1PingResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSodacardsDevpublicV1PingResponseWithDefaults() *SodacardsDevpublicV1PingResponse {
	this := SodacardsDevpublicV1PingResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1PingResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1PingResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1PingResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *SodacardsDevpublicV1PingResponse) SetStatus(v string) {
	o.Status = &v
}

// GetEnvironment returns the Environment field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1PingResponse) GetEnvironment() string {
	if o == nil || IsNil(o.Environment) {
		var ret string
		return ret
	}
	return *o.Environment
}

// GetEnvironmentOk returns a tuple with the Environment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1PingResponse) GetEnvironmentOk() (*string, bool) {
	if o == nil || IsNil(o.Environment) {
		return nil, false
	}
	return o.Environment, true
}

// HasEnvironment returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1PingResponse) HasEnvironment() bool {
	if o != nil && !IsNil(o.Environment) {
		return true
	}

	return false
}

// SetEnvironment gets a reference to the given string and assigns it to the Environment field.
func (o *SodacardsDevpublicV1PingResponse) SetEnvironment(v string) {
	o.Environment = &v
}

// GetResellerId returns the ResellerId field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1PingResponse) GetResellerId() string {
	if o == nil || IsNil(o.ResellerId) {
		var ret string
		return ret
	}
	return *o.ResellerId
}

// GetResellerIdOk returns a tuple with the ResellerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1PingResponse) GetResellerIdOk() (*string, bool) {
	if o == nil || IsNil(o.ResellerId) {
		return nil, false
	}
	return o.ResellerId, true
}

// HasResellerId returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1PingResponse) HasResellerId() bool {
	if o != nil && !IsNil(o.ResellerId) {
		return true
	}

	return false
}

// SetResellerId gets a reference to the given string and assigns it to the ResellerId field.
func (o *SodacardsDevpublicV1PingResponse) SetResellerId(v string) {
	o.ResellerId = &v
}

func (o SodacardsDevpublicV1PingResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SodacardsDevpublicV1PingResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Environment) {
		toSerialize["environment"] = o.Environment
	}
	if !IsNil(o.ResellerId) {
		toSerialize["resellerId"] = o.ResellerId
	}
	return toSerialize, nil
}

type NullableSodacardsDevpublicV1PingResponse struct {
	value *SodacardsDevpublicV1PingResponse
	isSet bool
}

func (v NullableSodacardsDevpublicV1PingResponse) Get() *SodacardsDevpublicV1PingResponse {
	return v.value
}

func (v *NullableSodacardsDevpublicV1PingResponse) Set(val *SodacardsDevpublicV1PingResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSodacardsDevpublicV1PingResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSodacardsDevpublicV1PingResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSodacardsDevpublicV1PingResponse(val *SodacardsDevpublicV1PingResponse) *NullableSodacardsDevpublicV1PingResponse {
	return &NullableSodacardsDevpublicV1PingResponse{value: val, isSet: true}
}

func (v NullableSodacardsDevpublicV1PingResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSodacardsDevpublicV1PingResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


