/*
SODACARDS Developer API

Sell gift cards and game top-ups from your own systems.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sodacards

import (
	"encoding/json"
)

// checks if the SodacardsDevpublicV1OrderItemInputFieldsEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SodacardsDevpublicV1OrderItemInputFieldsEntry{}

// SodacardsDevpublicV1OrderItemInputFieldsEntry struct for SodacardsDevpublicV1OrderItemInputFieldsEntry
type SodacardsDevpublicV1OrderItemInputFieldsEntry struct {
	Key *string `json:"key,omitempty"`
	Value *string `json:"value,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SodacardsDevpublicV1OrderItemInputFieldsEntry SodacardsDevpublicV1OrderItemInputFieldsEntry

// NewSodacardsDevpublicV1OrderItemInputFieldsEntry instantiates a new SodacardsDevpublicV1OrderItemInputFieldsEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSodacardsDevpublicV1OrderItemInputFieldsEntry() *SodacardsDevpublicV1OrderItemInputFieldsEntry {
	this := SodacardsDevpublicV1OrderItemInputFieldsEntry{}
	return &this
}

// NewSodacardsDevpublicV1OrderItemInputFieldsEntryWithDefaults instantiates a new SodacardsDevpublicV1OrderItemInputFieldsEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSodacardsDevpublicV1OrderItemInputFieldsEntryWithDefaults() *SodacardsDevpublicV1OrderItemInputFieldsEntry {
	this := SodacardsDevpublicV1OrderItemInputFieldsEntry{}
	return &this
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1OrderItemInputFieldsEntry) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1OrderItemInputFieldsEntry) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1OrderItemInputFieldsEntry) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *SodacardsDevpublicV1OrderItemInputFieldsEntry) SetKey(v string) {
	o.Key = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1OrderItemInputFieldsEntry) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1OrderItemInputFieldsEntry) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1OrderItemInputFieldsEntry) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *SodacardsDevpublicV1OrderItemInputFieldsEntry) SetValue(v string) {
	o.Value = &v
}

func (o SodacardsDevpublicV1OrderItemInputFieldsEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SodacardsDevpublicV1OrderItemInputFieldsEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SodacardsDevpublicV1OrderItemInputFieldsEntry) UnmarshalJSON(data []byte) (err error) {
	varSodacardsDevpublicV1OrderItemInputFieldsEntry := _SodacardsDevpublicV1OrderItemInputFieldsEntry{}

	err = json.Unmarshal(data, &varSodacardsDevpublicV1OrderItemInputFieldsEntry)

	if err != nil {
		return err
	}

	*o = SodacardsDevpublicV1OrderItemInputFieldsEntry(varSodacardsDevpublicV1OrderItemInputFieldsEntry)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "key")
		delete(additionalProperties, "value")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSodacardsDevpublicV1OrderItemInputFieldsEntry struct {
	value *SodacardsDevpublicV1OrderItemInputFieldsEntry
	isSet bool
}

func (v NullableSodacardsDevpublicV1OrderItemInputFieldsEntry) Get() *SodacardsDevpublicV1OrderItemInputFieldsEntry {
	return v.value
}

func (v *NullableSodacardsDevpublicV1OrderItemInputFieldsEntry) Set(val *SodacardsDevpublicV1OrderItemInputFieldsEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableSodacardsDevpublicV1OrderItemInputFieldsEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableSodacardsDevpublicV1OrderItemInputFieldsEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSodacardsDevpublicV1OrderItemInputFieldsEntry(val *SodacardsDevpublicV1OrderItemInputFieldsEntry) *NullableSodacardsDevpublicV1OrderItemInputFieldsEntry {
	return &NullableSodacardsDevpublicV1OrderItemInputFieldsEntry{value: val, isSet: true}
}

func (v NullableSodacardsDevpublicV1OrderItemInputFieldsEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSodacardsDevpublicV1OrderItemInputFieldsEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


