/*
SODACARDS Developer API

Sell gift cards and game top-ups from your own systems.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sodacards

import (
	"encoding/json"
)

// checks if the SodacardsDevpublicV1RotateWebhookSecretResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SodacardsDevpublicV1RotateWebhookSecretResponse{}

// SodacardsDevpublicV1RotateWebhookSecretResponse struct for SodacardsDevpublicV1RotateWebhookSecretResponse
type SodacardsDevpublicV1RotateWebhookSecretResponse struct {
	// secret is the new signing secret, shown only once, like at registration.
	Secret *string `json:"secret,omitempty"`
	// prev_secret_expires_at is when the previous secret stops being accepted  (RFC 3339). Until then both secrets validate a delivery.
	PrevSecretExpiresAt *string `json:"prevSecretExpiresAt,omitempty"`
}

// NewSodacardsDevpublicV1RotateWebhookSecretResponse instantiates a new SodacardsDevpublicV1RotateWebhookSecretResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSodacardsDevpublicV1RotateWebhookSecretResponse() *SodacardsDevpublicV1RotateWebhookSecretResponse {
	this := SodacardsDevpublicV1RotateWebhookSecretResponse{}
	return &this
}

// NewSodacardsDevpublicV1RotateWebhookSecretResponseWithDefaults instantiates a new SodacardsDevpublicV1RotateWebhookSecretResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSodacardsDevpublicV1RotateWebhookSecretResponseWithDefaults() *SodacardsDevpublicV1RotateWebhookSecretResponse {
	this := SodacardsDevpublicV1RotateWebhookSecretResponse{}
	return &this
}

// GetSecret returns the Secret field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1RotateWebhookSecretResponse) GetSecret() string {
	if o == nil || IsNil(o.Secret) {
		var ret string
		return ret
	}
	return *o.Secret
}

// GetSecretOk returns a tuple with the Secret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1RotateWebhookSecretResponse) GetSecretOk() (*string, bool) {
	if o == nil || IsNil(o.Secret) {
		return nil, false
	}
	return o.Secret, true
}

// HasSecret returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1RotateWebhookSecretResponse) HasSecret() bool {
	if o != nil && !IsNil(o.Secret) {
		return true
	}

	return false
}

// SetSecret gets a reference to the given string and assigns it to the Secret field.
func (o *SodacardsDevpublicV1RotateWebhookSecretResponse) SetSecret(v string) {
	o.Secret = &v
}

// GetPrevSecretExpiresAt returns the PrevSecretExpiresAt field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1RotateWebhookSecretResponse) GetPrevSecretExpiresAt() string {
	if o == nil || IsNil(o.PrevSecretExpiresAt) {
		var ret string
		return ret
	}
	return *o.PrevSecretExpiresAt
}

// GetPrevSecretExpiresAtOk returns a tuple with the PrevSecretExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1RotateWebhookSecretResponse) GetPrevSecretExpiresAtOk() (*string, bool) {
	if o == nil || IsNil(o.PrevSecretExpiresAt) {
		return nil, false
	}
	return o.PrevSecretExpiresAt, true
}

// HasPrevSecretExpiresAt returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1RotateWebhookSecretResponse) HasPrevSecretExpiresAt() bool {
	if o != nil && !IsNil(o.PrevSecretExpiresAt) {
		return true
	}

	return false
}

// SetPrevSecretExpiresAt gets a reference to the given string and assigns it to the PrevSecretExpiresAt field.
func (o *SodacardsDevpublicV1RotateWebhookSecretResponse) SetPrevSecretExpiresAt(v string) {
	o.PrevSecretExpiresAt = &v
}

func (o SodacardsDevpublicV1RotateWebhookSecretResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SodacardsDevpublicV1RotateWebhookSecretResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Secret) {
		toSerialize["secret"] = o.Secret
	}
	if !IsNil(o.PrevSecretExpiresAt) {
		toSerialize["prevSecretExpiresAt"] = o.PrevSecretExpiresAt
	}
	return toSerialize, nil
}

type NullableSodacardsDevpublicV1RotateWebhookSecretResponse struct {
	value *SodacardsDevpublicV1RotateWebhookSecretResponse
	isSet bool
}

func (v NullableSodacardsDevpublicV1RotateWebhookSecretResponse) Get() *SodacardsDevpublicV1RotateWebhookSecretResponse {
	return v.value
}

func (v *NullableSodacardsDevpublicV1RotateWebhookSecretResponse) Set(val *SodacardsDevpublicV1RotateWebhookSecretResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSodacardsDevpublicV1RotateWebhookSecretResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSodacardsDevpublicV1RotateWebhookSecretResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSodacardsDevpublicV1RotateWebhookSecretResponse(val *SodacardsDevpublicV1RotateWebhookSecretResponse) *NullableSodacardsDevpublicV1RotateWebhookSecretResponse {
	return &NullableSodacardsDevpublicV1RotateWebhookSecretResponse{value: val, isSet: true}
}

func (v NullableSodacardsDevpublicV1RotateWebhookSecretResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSodacardsDevpublicV1RotateWebhookSecretResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


