/*
SODACARDS Developer API

Sell gift cards and game top-ups from your own systems.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sodacards

import (
	"encoding/json"
)

// checks if the SodacardsDevpublicV1RegisterWebhookRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SodacardsDevpublicV1RegisterWebhookRequest{}

// SodacardsDevpublicV1RegisterWebhookRequest struct for SodacardsDevpublicV1RegisterWebhookRequest
type SodacardsDevpublicV1RegisterWebhookRequest struct {
	// url is the HTTPS endpoint to deliver events to.
	Url *string `json:"url,omitempty"`
	// events are the event types to subscribe to (at least one), e.g.  \"order.fulfilled\", \"order.needs_attention\", \"order.refunded\", \"wallet.low_balance\",  \"wallet.credited\".
	Events []string `json:"events,omitempty"`
}

// NewSodacardsDevpublicV1RegisterWebhookRequest instantiates a new SodacardsDevpublicV1RegisterWebhookRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSodacardsDevpublicV1RegisterWebhookRequest() *SodacardsDevpublicV1RegisterWebhookRequest {
	this := SodacardsDevpublicV1RegisterWebhookRequest{}
	return &this
}

// NewSodacardsDevpublicV1RegisterWebhookRequestWithDefaults instantiates a new SodacardsDevpublicV1RegisterWebhookRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSodacardsDevpublicV1RegisterWebhookRequestWithDefaults() *SodacardsDevpublicV1RegisterWebhookRequest {
	this := SodacardsDevpublicV1RegisterWebhookRequest{}
	return &this
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1RegisterWebhookRequest) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1RegisterWebhookRequest) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1RegisterWebhookRequest) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *SodacardsDevpublicV1RegisterWebhookRequest) SetUrl(v string) {
	o.Url = &v
}

// GetEvents returns the Events field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1RegisterWebhookRequest) GetEvents() []string {
	if o == nil || IsNil(o.Events) {
		var ret []string
		return ret
	}
	return o.Events
}

// GetEventsOk returns a tuple with the Events field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1RegisterWebhookRequest) GetEventsOk() ([]string, bool) {
	if o == nil || IsNil(o.Events) {
		return nil, false
	}
	return o.Events, true
}

// HasEvents returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1RegisterWebhookRequest) HasEvents() bool {
	if o != nil && !IsNil(o.Events) {
		return true
	}

	return false
}

// SetEvents gets a reference to the given []string and assigns it to the Events field.
func (o *SodacardsDevpublicV1RegisterWebhookRequest) SetEvents(v []string) {
	o.Events = v
}

func (o SodacardsDevpublicV1RegisterWebhookRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SodacardsDevpublicV1RegisterWebhookRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Events) {
		toSerialize["events"] = o.Events
	}
	return toSerialize, nil
}

type NullableSodacardsDevpublicV1RegisterWebhookRequest struct {
	value *SodacardsDevpublicV1RegisterWebhookRequest
	isSet bool
}

func (v NullableSodacardsDevpublicV1RegisterWebhookRequest) Get() *SodacardsDevpublicV1RegisterWebhookRequest {
	return v.value
}

func (v *NullableSodacardsDevpublicV1RegisterWebhookRequest) Set(val *SodacardsDevpublicV1RegisterWebhookRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSodacardsDevpublicV1RegisterWebhookRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSodacardsDevpublicV1RegisterWebhookRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSodacardsDevpublicV1RegisterWebhookRequest(val *SodacardsDevpublicV1RegisterWebhookRequest) *NullableSodacardsDevpublicV1RegisterWebhookRequest {
	return &NullableSodacardsDevpublicV1RegisterWebhookRequest{value: val, isSet: true}
}

func (v NullableSodacardsDevpublicV1RegisterWebhookRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSodacardsDevpublicV1RegisterWebhookRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


