/*
SODACARDS Developer API

Sell gift cards and game top-ups from your own systems.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sodacards

import (
	"encoding/json"
)

// checks if the SodacardsDevpublicV1OrderLine type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SodacardsDevpublicV1OrderLine{}

// SodacardsDevpublicV1OrderLine OrderLine is one product to buy on an order. input_fields carries the  purchase-form values a product requires (for example a game player id), keyed  by the field name from the product definition.
type SodacardsDevpublicV1OrderLine struct {
	// product_id is the id of the product to buy (a catalog product id).
	ProductId *string `json:"productId,omitempty"`
	// quantity is how many units to buy on this line (at least one).
	Quantity *int32 `json:"quantity,omitempty"`
	// input_fields holds the required purchase-form values, keyed by field name.
	InputFields map[string]string `json:"inputFields,omitempty"`
}

// NewSodacardsDevpublicV1OrderLine instantiates a new SodacardsDevpublicV1OrderLine object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSodacardsDevpublicV1OrderLine() *SodacardsDevpublicV1OrderLine {
	this := SodacardsDevpublicV1OrderLine{}
	return &this
}

// NewSodacardsDevpublicV1OrderLineWithDefaults instantiates a new SodacardsDevpublicV1OrderLine object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSodacardsDevpublicV1OrderLineWithDefaults() *SodacardsDevpublicV1OrderLine {
	this := SodacardsDevpublicV1OrderLine{}
	return &this
}

// GetProductId returns the ProductId field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1OrderLine) GetProductId() string {
	if o == nil || IsNil(o.ProductId) {
		var ret string
		return ret
	}
	return *o.ProductId
}

// GetProductIdOk returns a tuple with the ProductId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1OrderLine) GetProductIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProductId) {
		return nil, false
	}
	return o.ProductId, true
}

// HasProductId returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1OrderLine) HasProductId() bool {
	if o != nil && !IsNil(o.ProductId) {
		return true
	}

	return false
}

// SetProductId gets a reference to the given string and assigns it to the ProductId field.
func (o *SodacardsDevpublicV1OrderLine) SetProductId(v string) {
	o.ProductId = &v
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1OrderLine) GetQuantity() int32 {
	if o == nil || IsNil(o.Quantity) {
		var ret int32
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1OrderLine) GetQuantityOk() (*int32, bool) {
	if o == nil || IsNil(o.Quantity) {
		return nil, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1OrderLine) HasQuantity() bool {
	if o != nil && !IsNil(o.Quantity) {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given int32 and assigns it to the Quantity field.
func (o *SodacardsDevpublicV1OrderLine) SetQuantity(v int32) {
	o.Quantity = &v
}

// GetInputFields returns the InputFields field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1OrderLine) GetInputFields() map[string]string {
	if o == nil || IsNil(o.InputFields) {
		var ret map[string]string
		return ret
	}
	return o.InputFields
}

// GetInputFieldsOk returns a tuple with the InputFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1OrderLine) GetInputFieldsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.InputFields) {
		return map[string]string{}, false
	}
	return o.InputFields, true
}

// HasInputFields returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1OrderLine) HasInputFields() bool {
	if o != nil && !IsNil(o.InputFields) {
		return true
	}

	return false
}

// SetInputFields gets a reference to the given map[string]string and assigns it to the InputFields field.
func (o *SodacardsDevpublicV1OrderLine) SetInputFields(v map[string]string) {
	o.InputFields = v
}

func (o SodacardsDevpublicV1OrderLine) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SodacardsDevpublicV1OrderLine) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ProductId) {
		toSerialize["productId"] = o.ProductId
	}
	if !IsNil(o.Quantity) {
		toSerialize["quantity"] = o.Quantity
	}
	if !IsNil(o.InputFields) {
		toSerialize["inputFields"] = o.InputFields
	}
	return toSerialize, nil
}

type NullableSodacardsDevpublicV1OrderLine struct {
	value *SodacardsDevpublicV1OrderLine
	isSet bool
}

func (v NullableSodacardsDevpublicV1OrderLine) Get() *SodacardsDevpublicV1OrderLine {
	return v.value
}

func (v *NullableSodacardsDevpublicV1OrderLine) Set(val *SodacardsDevpublicV1OrderLine) {
	v.value = val
	v.isSet = true
}

func (v NullableSodacardsDevpublicV1OrderLine) IsSet() bool {
	return v.isSet
}

func (v *NullableSodacardsDevpublicV1OrderLine) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSodacardsDevpublicV1OrderLine(val *SodacardsDevpublicV1OrderLine) *NullableSodacardsDevpublicV1OrderLine {
	return &NullableSodacardsDevpublicV1OrderLine{value: val, isSet: true}
}

func (v NullableSodacardsDevpublicV1OrderLine) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSodacardsDevpublicV1OrderLine) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


