/*
SODACARDS Developer API

Sell gift cards and game top-ups from your own systems.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sodacards

import (
	"encoding/json"
)

// checks if the SodacardsDevpublicV1GetOrderResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SodacardsDevpublicV1GetOrderResponse{}

// SodacardsDevpublicV1GetOrderResponse struct for SodacardsDevpublicV1GetOrderResponse
type SodacardsDevpublicV1GetOrderResponse struct {
	// order is the requested order.
	Order *SodacardsDevpublicV1Order `json:"order,omitempty"`
}

// NewSodacardsDevpublicV1GetOrderResponse instantiates a new SodacardsDevpublicV1GetOrderResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSodacardsDevpublicV1GetOrderResponse() *SodacardsDevpublicV1GetOrderResponse {
	this := SodacardsDevpublicV1GetOrderResponse{}
	return &this
}

// NewSodacardsDevpublicV1GetOrderResponseWithDefaults instantiates a new SodacardsDevpublicV1GetOrderResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSodacardsDevpublicV1GetOrderResponseWithDefaults() *SodacardsDevpublicV1GetOrderResponse {
	this := SodacardsDevpublicV1GetOrderResponse{}
	return &this
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *SodacardsDevpublicV1GetOrderResponse) GetOrder() SodacardsDevpublicV1Order {
	if o == nil || IsNil(o.Order) {
		var ret SodacardsDevpublicV1Order
		return ret
	}
	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SodacardsDevpublicV1GetOrderResponse) GetOrderOk() (*SodacardsDevpublicV1Order, bool) {
	if o == nil || IsNil(o.Order) {
		return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *SodacardsDevpublicV1GetOrderResponse) HasOrder() bool {
	if o != nil && !IsNil(o.Order) {
		return true
	}

	return false
}

// SetOrder gets a reference to the given SodacardsDevpublicV1Order and assigns it to the Order field.
func (o *SodacardsDevpublicV1GetOrderResponse) SetOrder(v SodacardsDevpublicV1Order) {
	o.Order = &v
}

func (o SodacardsDevpublicV1GetOrderResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SodacardsDevpublicV1GetOrderResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Order) {
		toSerialize["order"] = o.Order
	}
	return toSerialize, nil
}

type NullableSodacardsDevpublicV1GetOrderResponse struct {
	value *SodacardsDevpublicV1GetOrderResponse
	isSet bool
}

func (v NullableSodacardsDevpublicV1GetOrderResponse) Get() *SodacardsDevpublicV1GetOrderResponse {
	return v.value
}

func (v *NullableSodacardsDevpublicV1GetOrderResponse) Set(val *SodacardsDevpublicV1GetOrderResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSodacardsDevpublicV1GetOrderResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSodacardsDevpublicV1GetOrderResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSodacardsDevpublicV1GetOrderResponse(val *SodacardsDevpublicV1GetOrderResponse) *NullableSodacardsDevpublicV1GetOrderResponse {
	return &NullableSodacardsDevpublicV1GetOrderResponse{value: val, isSet: true}
}

func (v NullableSodacardsDevpublicV1GetOrderResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSodacardsDevpublicV1GetOrderResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


